### ISSUE TITLE
System no longer starting up (port in use for database)

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#100]
I started a new model server using llama_cpp_server with the following command
python3 -m llama_cpp.server --model ~/dev/models/codellama-13b.Q5_K_M.gguf --n_gpu_layers 35 --n_batch 12000

This starts a server on port 8000 and I can use URLs such as http://localhost:8000/v1/models to get list of moidels

I then entered this as a new model on bionicGPT 
tried a few requests but carried on getting error, I then noticed that the backend had gone into what looked like a loop and kept printing out the following lines

dev-llm-api-1         | {"timestamp":"2023-11-13T15:47:33.800558Z","level":"INFO","fields":{"message":"chat client closed channel"},"target":"cria::routes::chat","span":{"name":"infer"},"spans":[{"name":"infer"}]}
dev-llm-api-1         | {"timestamp":"2023-11-13T15:47:34.026322Z","level":"INFO","fields":{"message":"chat client closed channel"},"target":"cria::routes::chat","span":{"name":"infer"},"spans":[{"name":"infer"}]}
dev-llm-api-1         | {"timestamp":"2023-11-13T15:47:34.274711Z","level":"INFO","fields":{"message":"chat client closed channel"},"target":"cria::routes::chat","span":{"name":"infer"},"spans":[{"name":"infer"}]}
dev-llm-api-1         | {"timestamp":"2023-11-13T15:47:34.487666Z","level":"INFO","fields":{"message":"chat client closed channel"},"target":"cria::routes::chat","span":{"name":"infer"},"spans":[{"name":"infer"}]}
dev-llm-api-1         | {"timestamp":"2023-11-13T15:47:34.768007Z","level":"INFO","fields":{"message":"chat client closed channel"},"target":"cria::routes::chat","span":{"name":"infer"},"spans":[{"name":"infer"}]}

I killed the backend and tried to start it again, but kepty getting

dev-envoy-1           | [2023-11-13 15:51:26.676][1][info][config] [source/server/configuration_impl.cc:125] loading tracing configuration
dev-envoy-1           | [2023-11-13 15:51:26.676][1][info][config] [source/server/configuration_impl.cc:85] loading 0 static secret(s)
dev-envoy-1           | [2023-11-13 15:51:26.676][1][info][config] [source/server/configuration_impl.cc:91] loading 2 cluster(s)
dev-envoy-1           | [2023-11-13 15:51:26.677][1][info][config] [source/server/configuration_impl.cc:95] loading 1 listener(s)
dev-envoy-1           | [2023-11-13 15:51:26.681][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.extensions.filters.http.ext_authz.v3.ExtAuthz Using the default now-deprecated value AUTO for enum 'envoy.extensions.filters.http.ext_authz.v3.ExtAuthz.transport_api_version' from file ext_authz.proto. This enum value will be removed from Envoy soon so a non-default value must now be explicitly set. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
dev-envoy-1           | [2023-11-13 15:51:26.682][1][info][config] [source/server/configuration_impl.cc:107] loading stats configuration
dev-envoy-1           | [2023-11-13 15:51:26.682][1][info][main] [source/server/server.cc:732] starting main dispatch loop
dev-envoy-1           | [2023-11-13 15:51:26.683][1][info][runtime] [source/common/runtime/runtime_impl.cc:425] RTDS has finished initialization
dev-envoy-1           | [2023-11-13 15:51:26.683][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:191] cm init: all clusters initialized
dev-envoy-1           | [2023-11-13 15:51:26.683][1][info][main] [source/server/server.cc:713] all clusters initialized. initializing init manager
dev-envoy-1           | [2023-11-13 15:51:26.683][1][info][config] [source/server/listener_manager_impl.cc:888] all dependencies initialized. starting workers
dev-envoy-1           | [2023-11-13 15:51:26.685][1][warning][main] [source/server/server.cc:610] there is no configured limit to the number of allowed active connections. Set a limit via the runtime key overload.global_downstream_max_connections
dev-embeddings-api-1  | 2023-11-13T15:51:28.790229Z  INFO text_embeddings_router: router/src/main.rs:149: Args { model_id: "BAAI/bge-small-en-v1.5", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, hf_api_token: None, hostname: "a7e9a82196cf", port: 80, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: Some("/data"), json_output: false, otlp_endpoint: None, cors_allow_origin: None }
dev-embeddings-api-1  | 2023-11-13T15:51:28.790379Z  INFO hf_hub: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hf-hub-0.3.2/src/lib.rs:55: Token file not found "/root/.cache/huggingface/token"    
dev-embeddings-api-1  | 2023-11-13T15:51:28.873308Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:9: Starting download
dev-db-1              | 
dev-db-1              | PostgreSQL Database directory appears to contain a database; Skipping initialization
dev-db-1              | 
Error response from daemon: driver failed programming external connectivity on endpoint dev-unstructured-1 (fddca92eba315eaf62efe4b60c975bf08097cbae0773b7ba9feccaa78b7b8dee): Error starting userland proxy: listen tcp4 0.0.0.0:8000: bind: address already in us

I even stopped all docker processes manually and retried. Everytime I get the same DB port in use error

**Comment by ianpurton** [comment]
Can you show a screen shot of the page where you add the model, so I can see the URL.

So the llama_cpp server runs on 8000 and there's a conflict with?

**Comment by kulbinderdio** [comment]
closing as I was being stupid
