### ISSUE TITLE
Upload documents API : can you provide a usage example ?

### ISSUE THREAD

**Issue by XmasRock** [bionic-gpt/bionic-gpt#102]
Hi,
First congratulations for this wonderful project !

I've produced a large list of text files I want to use as documents. 
Uploading through the UI will be a bit tedious.
I've created a pipeline which is giving me an API Key, but I can't find the API doc.
Any pointer I can look at ?

**Comment by ianpurton** [comment]
Hi, we only added the feature yesterday :)

I'm writing the docs now and I'll post a link when I have something up (2 to 3 hours)

Thanks

**Comment by ianpurton** [comment]
Documentation is here https://bionic-gpt.com/docs/document-pipeline/introduction/

You'll need to upgrade to the latest `docker-compose.yml` as we needed to fix an issue with upload sie.
