### ISSUE TITLE
Using GPU after uploading a doc ?

### ISSUE THREAD

**Issue by XmasRock** [bionic-gpt/bionic-gpt#103]
I've uploaded a 3MB txt file, there's 2247 chunks to process, my CPU (i7) is 100% my 16GB RAM is at 82%.
After 10mins there's still 1800 chunks to process.

None of my 2 GPUs are used (from a nVidia T1000)
Is there a way to use the GPU ?

**Comment by ianpurton** [comment]
We are using https://github.com/huggingface/text-embeddings-inference

We're using the CPU docker image. https://github.com/huggingface/text-embeddings-inference#docker-images

It should be possible to switch to a GPU image.

I will document this as there's a couple of other things to be aware of when running GPU and docker.

**Comment by Cheizr** [comment]
bionicgpt works great, thanks Ian, GPU would be a big performance improvement

**Comment by ianpurton** [comment]
Could you give https://bionic-gpt.com/docs/administration/gpu-embeddings/ a try
