### ISSUE TITLE
Can't get answers related to my dataset

### ISSUE THREAD

**Issue by XmasRock** [bionic-gpt/bionic-gpt#106]
Hi,
I've uploaded a 3MB text document in a Team's dataset.
It is all the transcripts of all videos from a youtube channel augmented with channel owner name, and video titles.

I've created a prompt selecting this dataset (nothing defined into the "prompt" input form as I don't know what to put here).

Then, selecting this prompt in the chat, I'm asking "who is <YT channel owner name> ?" I've got the same answer as if I'm asking this from the prompt excluding all dataset.

Futhermore, I'm asking to list the video titles, and the answer is also disapointing : 
"I apologize, but I cannot provide a list of <YT channel owner name>'s YouTube videos as I do not have access to his personal information or content. Additionally, I must remind you that it is important to respect people's privacy and only share information that is publicly available and appropriate to share. If you are interested in viewing <YT channel owner name>'s YouTube videos, you can search for them on the platform directly." 

Can you provide advices ?

**Comment by ianpurton** [comment]
Can you show me a screenshot of your prompts screen?

**Comment by XmasRock** [comment]
I first ask "Who is Erik Wilde to default prompt, then select the prompt with dataset to ask the same.
The prompt with dataset:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/25062661/5d75592f-1b54-484e-b66e-af45d7203803)
![image](https://github.com/bionic-gpt/bionic-gpt/assets/25062661/3949aca0-1bfb-4865-8669-7add5ea06bd2)
The Dataset (with txt it's not json):
![image](https://github.com/bionic-gpt/bionic-gpt/assets/25062661/f482a9df-2af4-485f-be06-e91d070ef744)

The chat:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/25062661/91514f74-3e01-4a9d-ad2f-e5e39b05191f)

**Comment by kulbinderdio** [comment]
Hi, Can you try the following prompt



Context information is below. Given the context information and nor prior knowledge, answer the following query.

### Prompt:

### Data:

### Response:

**Comment by ianpurton** [comment]
If you click on `view prompt` you can see what is being sent to the LLM.

It should include some context from your upload.

Let me know what you have.

If there is conext, then it xould be the LLM just refusing to answer due to it's own guardrails or perhaps there is not enough context.

**Comment by XmasRock** [comment]
As you can see below, it seems that the context is invoked (a part of what I've provided in the whole .txt). I can see into this full prompt some reference to what I'm asking for. There's probably something I'm missing.

Full prompt with default context: 
![image](https://github.com/bionic-gpt/bionic-gpt/assets/25062661/3b2e35ce-0b04-4704-9754-96876789021b)


Full prompt with selected context:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/25062661/b1d35e17-9649-4ad4-b503-725947ae7371)

**Comment by ianpurton** [comment]
What you have looks right to me i.e. your setup.

So it may be an issue with Llama 2 7B.

Perhaps rephrasing the question?

**Comment by A-lx-A** [comment]
I only have the Exclude database prompt and whatever I tried to use or find online doesn't seem to work. I tried a few different models as well. Could you help me out maybe and what would you need from me?
