### ISSUE TITLE
Integrate Stable Diffusion into bionicGPT

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#111]
A project that builds a docker container for this already exists under

https://github.com/AbdBarho/stable-diffusion-webui-docker

**Instructions**
git clone https://github.com/AbdBarho/stable-diffusion-webui-docker
cd stable-diffusion-webui-docker
docker compose --profile auto up --build

**Comment by ianpurton** [comment]
Stable diffusion docker as an API https://github.com/kiri-art/docker-diffusers-api

This requires Nvidia.

**Comment by ianpurton** [comment]
Add to roadmap
