### ISSUE TITLE
Proxy between Bionic and Text Generation Providers

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#118]
At the moment we rely on providers to provide an Open AI compatible Rest API.

[TGI](https://github.com/huggingface/text-generation-inference) for example doesn't support Open AI, but is our best candidate for a production inference engine.

## Requirements

- High performace async with no blocking on IO.
- Versioned docker container
- Supports the [/chat/completions](https://platform.openai.com/docs/guides/text-generation/chat-completions-api) end point
- Support temperature, max_tokens etc.

### Possible Solution - Lite LLM

[Lite LLM](https://github.com/BerriAI/litellm) - Call all LLM APIs using the OpenAI format. Use Bedrock, Azure, OpenAI, Cohere, Anthropic, Ollama, Sagemaker, HuggingFace, Replicate (100+ LLMs)

Problems

- Written in Python so not sure how this will perform under load. 
- Not async at the moment - see https://github.com/BerriAI/litellm/issues/839
- They can't seem to build a container - https://github.com/BerriAI/litellm/issues/723

### Possible Solution - Build our own

Either create a proxy, or add code to Bionic specific for TGI.

- Which APIs already support Open AI
- How much work would this be
- Which providers to support.

**Comment by ishaan-jaff** [comment]
@ianpurton I'm the maintainer of LiteLLM. We load test our proxy, 
- it's built to maixmise throughput and can handle 500+ requests/second 
- it is completely async 
- looking into the container issue now 

How can we help with adding the proxy ?
