### ISSUE TITLE
Airbyte integration

### ISSUE THREAD

**Issue by myrulezzz** [bionic-gpt/bionic-gpt#135]
What should be the target connection in airbyte to embed data? Also are you compatible with litellm?

**Comment by kulbinderdio** [comment]
Hi
We are compatible with liteLLM. We have a test configuration running HuggingFaces TGI, pointed to by liteLLM which in turn is called by bionicGPT.  In fact we worked with the guys to iron out some issues with liteLLM so it would work in this configuration

Here are the scripts we use (on Linux)
1. Start up TGI (in Docker)
model =TheBloke/zephyr-7B-beta-AWQ
volume=$PWD/models
sudo docker run --gpus all --shm-size 1g -p 8080:80 -v $volume:/data ghcr.io/huggingface/text-generation-inference:latest --model-id $model --num-shard $num_shard --max-batch-prefill-tokens 2048 --quantize awq

2. start liteLLM
litellm --model huggingface/TheBloke/Yarn-Mistral-7B-128k-AWQ --api_base http://0.0.0.0:8080/generate_stream --host 0.0.0.0 --port 6789 --debug

3. Setup bionic to point to liteLLM
Create new model with url of 
http://<yourip-address>:6789/v1

This setup allows us to run almost any of the 325K+ models available on HuggingFace
Once the liteLLM guys have it successfully building a docker we can dockerise the full setup

**Comment by kulbinderdio** [comment]
$num_shard should be set to the number of GPUs you have

**Comment by kulbinderdio** [comment]
We haven't tried with AirByte yet (that I'm aware of).
Would you be looking at bionicGPT as a source or a destination?

**Comment by myrulezzz** [comment]
Ok thanks.so for airbyte how do you integrate with airbyte?what should be the target endpoint in airbyte to sync with bionic gpt?

**Comment by myrulezzz** [comment]
Target.So i have a source connector taking data from somewhere else and make them visible to bionic gpt. i am asking because you have airbyte in your kubernetes diagram

**Comment by kulbinderdio** [comment]
bionicGPT API is OpenAI API compatible, does airbyte allow connectivity to OpenAI?

If so, you can create a new Key in bionic and access it using that key and the url http://0.0.0.0:7800/v1

**Comment by kulbinderdio** [comment]
we have a test setup accessing the API using this from Jupyter Notebook

**Comment by kulbinderdio** [comment]
I might have to wait for our CTO to answer that one

**Comment by andsty** [comment]
i have tried also to deploy an openai model compatible in runpod.io. I connect it to bionig gpt. When i use it without datasets is working. When i embed a document and i ask question with the chosen dataset is not returning an answer

**Comment by ishaan-jaff** [comment]
hi @kulbinderdio is our docker image not working for you ?

**Comment by ishaan-jaff** [comment]
Litellm docker:

https://github.com/BerriAI/litellm/blob/main/Dockerfile

**Comment by kulbinderdio** [comment]
do you have a built docker image?

**Comment by ishaan-jaff** [comment]
@kulbinderdio yes
dockerfile: https://github.com/BerriAI/litellm/blob/main/Dockerfile 

ghcr image: https://github.com/BerriAI/litellm/pkgs/container/litellm

**Comment by ishaan-jaff** [comment]
let me know if you run into any issues

**Comment by kulbinderdio** [comment]
An error occurred: Expecting value: line 1 column 1 (char 0)

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     172.17.0.1:51668 - "POST /v1/completions HTTP/1.1" 500 Internal Server Error

**Comment by kulbinderdio** [comment]
@myrulezzz does this help
https://bionic-gpt.com/docs/document-pipeline/introduction/

**Comment by andsty** [comment]
Nope this is an api. How can i integrate this api with airbyte?

**Comment by ianpurton** [comment]
@andsty I haven't finished the Airbyte integration yet. I was hoping to find a connector that would upload files to a Rest API.

So the strategy would be any source to a our upload API.

If I can't find a connector then I'll have to build one.

**Comment by myrulezzz** [comment]
But is not only api. The connector should include embeddings as well.It should be something similar to qtrand or chroma sink connector.if you see these connectors they have url details and then hou need to define embeddings as well

**Comment by ianpurton** [comment]
When you upload to our api we take care of embeddings in the background.

So an API key is attached to a dataset and as you upload files to the API, the dataset gets filled with the files, chunks and embeddings are created.

**Comment by ianpurton** [comment]
This is on the roadmap
