### ISSUE TITLE
Add also functionality to embed documents only with split

### ISSUE THREAD

**Issue by andsty** [bionic-gpt/bionic-gpt#143]
I see that there is something wrong with your embeddings. I don't know how you split the documents. You load the and you split the text in chunks. I am a bit confused with the options available throw UI. It seems that if you upload a document that is not well structured then it will not return proper results.
I have tested pdfs and they are working perfectl i have tried also docx files which might not have the same well structure but the answers are. not very accurate.
I am aware that there are different methods to load and split documents. Which way does bionic gpt does it and is there. Shouldn't it have more options according with the document uploading?

**Comment by ianpurton** [comment]
Hi @andsty 

We use unstructured for document parsing in particular their chunking functionality. https://unstructured-io.github.io/unstructured/core/chunking.html

At the moment they only chunk by title. As they add more options we can also add more.

**Comment by andsty** [comment]
So is there a specific format to follow to be accurate with all my documents? What about csvs?


Best Regards,



Andreas Stylianou
Operations Manager- Data and Databases



Cablenet Communication Systems PLC
41-49 Ay. Nicolaou Street, Nimeli Court, Block A, 3rd Floor
2408 Engomi, Nicosia, Cyprus
Tel. +357 22 294144 | Fax. +357 22 294 447
www.cablenet.com.cy<http://www.cablenet.com.cy/>

________________________________

**Comment by andsty** [comment]
[cyta_2022.pdf](https://github.com/bionic-gpt/bionic-gpt/files/13561398/cyta_2022.pdf)
So here is a pdf document. Which llama2 model should i use from huggingface to run it on runpod gpu and what prompt should i use to get accurate results?

**Comment by ianpurton** [comment]
OK. 

For models, I think Llama2 70B is good. Is it the best for your use case? I'm not sure.

For the prompt I can't help you. Part of what Bionic GPT is about is giving people the ability to try out RAG.

If you don't get the results you expect, that maybe an issue with Bionic or just an issue with RAG in general.

The model we supply out of the box is not as good as 70B.

![image](https://github.com/bionic-gpt/bionic-gpt/assets/36966/bb83be65-8747-4f0b-bfbe-4193bdaffeca)

**Comment by kulbinderdio** [comment]
Hi andy
There are several questions being asked in your last comment and I'll try my best to answer then in turn
1. To run with GPU please have a look at https://bionic-gpt.com/docs/running-locally/gpu-setup/
This setup uses TGI which means you can use almost any HuggingFace model
2. There are a few models that have been fine tuned for tabular data, this is a very active area of research. I haven't tried it yet but you could look at trying RUCAIBox/mtl-data-to-text 
3. Without knowing what specific question you have it's not possible to suggest suggest a prompt that might return the results you're after

**Comment by andsty** [comment]
Ok so you dont suggest  gguf models from theblome.correct?  So questions could be like  what is the financial status of the company or show me expenses or split reveneu into more detail.things like that.Also one more question.if i have dataset a whith prompt a and dataset b woth prompt b with completely different  docuemnts and prompts.From the chat ui when i switch prompt to prompt b it doesn't seem that the docs from dataset b are used. From my tests it seems that when you change prompt it doesnt mean that it change the knowledge base.sometimes you need to logout pogin again and go to the default prompt or play around with prompts in order for answers to be accurate


Best Regards,



Andreas Stylianou
Operations Manager- Data and Databases



Cablenet Communication Systems PLC
41-49 Ay. Nicolaou Street, Nimeli Court, Block A, 3rd Floor
2408 Engomi, Nicosia, Cyprus
Tel. +357 22 294144 | Fax. +357 22 294 447
www.cablenet.com.cy<http://www.cablenet.com.cy/>

________________________________

**Comment by myrulezzz** [comment]
> Ok so you dont suggest  gguf models from theblome.correct?  So questions could be like  what is the financial status of the company or show me expenses or split reveneu into more detail.things like that.Also one more question.if i have dataset a whith prompt a and dataset b woth prompt b with completely different  docuemnts and prompts.From the chat ui when i switch prompt to prompt b it doesn't seem that the docs from dataset b are used. From my tests it seems that when you change prompt it doesnt mean that it change the knowledge base.sometimes you need to logout pogin again and go to the default prompt or play around with prompts in order for answers to be accurate
> 
> 
> 
> 
> 
> Best Regards,
> 
> 
> 
> 
> 
> 
> 
> Andreas Stylianou
> 
> Operations Manager- Data and Databases
> 
> 
> 
> 
> 
> 
> 
> Cablenet Communication Systems PLC
> 
> 41-49 Ay. Nicolaou Street, Nimeli Court, Block A, 3rd Floor
> 
> 2408 Engomi, Nicosia, Cyprus
> 
> Tel. +357 22 294144 | Fax. +357 22 294 447
> 
> www.cablenet.com.cy<http://www.cablenet.com.cy/>
> 
> 
> 
> ________________________________
> 
> From: dio ***@***.***>
> 
> Sent: Tuesday, December 5, 2023 5:20:04 PM
> 
> To: bionic-gpt/bionic-gpt ***@***.***>
> 
> Cc: Andreas Stylianou ***@***.***>; Mention ***@***.***>
> 
> Subject: Re: [bionic-gpt/bionic-gpt] Add also functionality to embed documents only with split (Issue #143)
> 
> 
> 
> 
> 
> Hi andy
> 
> There are several questions being asked in your last comment and I'll try my best to answer then in turn
> 
> 
> 
>   1.  To run with GPU please have a look at https://bionic-gpt.com/docs/running-locally/gpu-setup/
> 
> This setup uses TGI which means you can use almost any HuggingFace model
> 
>   2.  There are a few models that have been fine tuned for tabular data, this is a very active area of research. I haven't tried it yet but you could look at trying RUCAIBox/mtl-data-to-text
> 
>   3.  Without knowing what specific question you have it's not possible to suggest suggest a prompt that might return the results you're after
>
