### ISSUE TITLE
Documents are just queued in Bionic GPT...

### ISSUE THREAD

**Issue by puckie62** [bionic-gpt/bionic-gpt#146]
Hi, I've tried to upload some documents but I can see that the Status has been "Queued" for a long time. What am I supposed to do?
Thanks in advance for any help!

**Comment by ianpurton** [comment]
@puckie62 Ca you do a `docker ps` and show us which processes are running?

**Comment by puckie62** [comment]
![docker ps](https://github.com/bionic-gpt/bionic-gpt/assets/113419145/5609125b-448e-42da-a015-ffc2a1d291da)
