### ISSUE TITLE
Unusably slow performance on m2 Pro 64gb

### ISSUE THREAD

**Issue by mirozahorak** [bionic-gpt/bionic-gpt#147]
Is there any way to use coreml?
i see that images are AMD64 and run in simulation.
Any plans for Apple compatible images?

**Comment by ianpurton** [comment]
@mirozahorak There's no plan for us to do Apple images. I did try but the CI/CD process was taking more than 1 hours.

However....

To get better performance with the model you could install one locally.

**Comment by mirozahorak** [comment]
i see, thanks, going to test it on 4090 instead for now

**Comment by ianpurton** [comment]
In which case you'll could follow our GPU setup https://bionic-gpt.com/docs/running-locally/gpu-setup/
