### ISSUE TITLE
422 errors on tcp connect while generating answers

### ISSUE THREAD

**Issue by mirozahorak** [bionic-gpt/bionic-gpt#149]
on all datasets i get this errors.

privategpt-unstructured-1    | 2023-12-05 14:05:33,769 uvicorn.error INFO Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
privategpt-migrations-1      | Writing: ./db/schema.sql
privategpt-migrations-1 exited with code 0
privategpt-app-1             | 2023-12-05T14:05:38.651161Z  INFO axum_server: listening on 0.0.0.0:7703
privategpt-app-1             | 2023-12-05T14:05:48.412851Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
privategpt-app-1             | 2023-12-05T14:05:48.413221Z  INFO axum_server::prompt: Retrieved 0 chunks
privategpt-app-1             | 2023-12-05T14:05:48.414721Z  INFO axum_server::prompt: Retrieved 0 history items
privategpt-app-1             | 2023-12-05T14:05:48.665531Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"
privategpt-app-1             | 2023-12-05T14:05:48.688392Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
privategpt-app-1             | 2023-12-05T14:05:48.688410Z  INFO axum_server::prompt: Retrieved 0 chunks
privategpt-app-1             | 2023-12-05T14:05:48.688757Z  INFO axum_server::prompt: Retrieved 0 history items
privategpt-app-1             | 2023-12-05T14:05:48.901666Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"
privategpt-app-1             | 2023-12-05T14:05:48.985628Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
privategpt-app-1             | 2023-12-05T14:05:48.985653Z  INFO axum_server::prompt: Retrieved 0 chunks
privategpt-app-1             | 2023-12-05T14:05:48.986795Z  INFO axum_server::prompt: Retrieved 0 history items
privategpt-app-1             | 2023-12-05T14:05:49.192342Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
privategpt-app-1             | 2023-12-05T14:05:49.192368Z  INFO axum_server::prompt: Retrieved 0 chunks
privategpt-app-1             | 2023-12-05T14:05:49.193765Z  INFO axum_server::prompt: Retrieved 0 history items
privategpt-app-1             | 2023-12-05T14:05:49.399696Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"
privategpt-app-1             | 2023-12-05T14:05:49.414271Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"

**Comment by ianpurton** [comment]
So we see this with apple silicon.

The inference engines are optimised to run on Linux.

So, same answer really.  There's localai where you can do a build for the m2 https://localai.io/basics/build/

We haven't found anything easier than that so far.
