### ISSUE TITLE
GPU setup does not startup without internet connection

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#157]
TGI is failing to startup with no network connection. The model used has been downloaded from previous run. Following stack trace

bionic-app-1             | 2023-12-07T13:45:31.795057Z  INFO axum_server: listening on 0.0.0.0:7703
bionic-tgi-1             | Error: DownloadError
bionic-tgi-1             | 2023-12-07T13:45:37.091652Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
bionic-tgi-1             |     sock = connection.create_connection(
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
bionic-tgi-1             |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/socket.py", line 955, in getaddrinfo
bionic-tgi-1             |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
bionic-tgi-1             | 
bionic-tgi-1             | socket.gaierror: [Errno -3] Temporary failure in name resolution
bionic-tgi-1             | 
bionic-tgi-1             | 
bionic-tgi-1             | The above exception was the direct cause of the following exception:
bionic-tgi-1             | 
bionic-tgi-1             | 
bionic-tgi-1             | Traceback (most recent call last):
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
bionic-tgi-1             |     response = self._make_request(
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 491, in _make_request
bionic-tgi-1             |     raise new_e
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 467, in _make_request
bionic-tgi-1             |     self._validate_conn(conn)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
bionic-tgi-1             |     conn.connect()
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
bionic-tgi-1             |     self.sock = sock = self._new_conn()
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
bionic-tgi-1             |     raise NameResolutionError(self.host, self, e) from e
bionic-tgi-1             | 
bionic-tgi-1             | urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f5b7b713700>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)
bionic-tgi-1             | 
bionic-tgi-1             | 
bionic-tgi-1             | The above exception was the direct cause of the following exception:
bionic-tgi-1             | 
bionic-tgi-1             | 
bionic-tgi-1             | Traceback (most recent call last):
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
bionic-tgi-1             |     resp = conn.urlopen(
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
bionic-tgi-1             |     retries = retries.increment(
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
bionic-tgi-1             |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
bionic-tgi-1             | 
bionic-tgi-1             | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/TheBloke/zephyr-7B-beta-AWQ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5b7b713700>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)"))
bionic-tgi-1             | 
bionic-tgi-1             | 
bionic-tgi-1             | During handling of the above exception, another exception occurred:
bionic-tgi-1             | 
bionic-tgi-1             | 
bionic-tgi-1             | Traceback (most recent call last):
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/bin/text-generation-server", line 8, in <module>
bionic-tgi-1             |     sys.exit(app())
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/cli.py", line 115, in download_weights
bionic-tgi-1             |     utils.weight_files(model_id, revision, extension)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 96, in weight_files
bionic-tgi-1             |     filenames = weight_hub_files(model_id, revision, extension)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/text_generation_server/utils/hub.py", line 25, in weight_hub_files
bionic-tgi-1             |     info = api.model_info(model_id, revision=revision)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
bionic-tgi-1             |     return fn(*args, **kwargs)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1677, in model_info
bionic-tgi-1             |     r = get_session().get(path, headers=headers, timeout=timeout, params=params)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
bionic-tgi-1             |     return self.request("GET", url, **kwargs)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
bionic-tgi-1             |     resp = self.send(prep, **send_kwargs)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
bionic-tgi-1             |     r = adapter.send(request, **kwargs)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
bionic-tgi-1             |     return super().send(request, *args, **kwargs)
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
bionic-tgi-1             |     raise ConnectionError(e, request=request)
bionic-tgi-1             | 
bionic-tgi-1             | requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/TheBloke/zephyr-7B-beta-AWQ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5b7b713700>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: 65dd5cde-9c3c-47c3-8f34-d30f9deadf30)')
bionic-tgi-1             | 
bionic-tgi-1             | 
bionic-tgi-1 exited with code 1

There is a YouTube video that references this and has a work around
https://www.youtube.com/watch?v=mpX6ByX80Jw

**Comment by kulbinderdio** [comment]
tried following config, specifying weights_cache_override
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:1.2
    command: --model-id TheBloke/zephyr-7B-beta-AWQ --max-batch-prefill-tokens 2048 --weights-cache-override ./models --quantize awq
    volumes:
      - ./models:/data


and get same error

bionic-tgi-1             | 2023-12-07T14:36:05.470803Z  INFO text_generation_launcher: Args { model_id: "TheBloke/zephyr-7B-beta-AWQ", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: Some(Awq), dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 2048, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "7341f2e02078", port: 80, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: Some("/data"), weights_cache_override: Some("./models"), disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
bionic-tgi-1             | 2023-12-07T14:36:05.470884Z  INFO download: text_generation_launcher: Starting download process.
bionic-unstructured-1    | 2023-12-07 14:36:05,832 unstructured_api INFO Started Unstructured API
bionic-unstructured-1    | 2023-12-07 14:36:05,832 uvicorn.error INFO Started server process [7]
bionic-unstructured-1    | 2023-12-07 14:36:05,833 uvicorn.error INFO Waiting for application startup.
bionic-unstructured-1    | 2023-12-07 14:36:05,833 uvicorn.error INFO Application startup complete.
bionic-unstructured-1    | 2023-12-07 14:36:05,834 uvicorn.error INFO Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
bionic-tgi-1             | Error: DownloadError
bionic-tgi-1             | 2023-12-07T14:36:07.573001Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):
bionic-tgi-1             | 
bionic-tgi-1             |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
bionic-tgi-1             |     sock = connection.create_connection(
bionic-tgi-1             | 
b

**Comment by ianpurton** [comment]
@kulbinderdio You didn't specify the `--huggingface-hub-cache`

Also please use the markdown features in github to format your issues. i.e. code and logs surrounded by ```

It's then easier to read.

**Comment by kulbinderdio** [comment]
Tried following

```
  tgi:
    image: ghcr.io/huggingface/text-generation-inference:1.2
    command: --model-id TheBloke/Llama-2-13B-chat-AWQ --max-batch-prefill-tokens 2048 --huggingface-hub-cache ./models --quantize awq
    volumes:
      - ./models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

Still getting issues when no network connection available

```
bionic-tgi-1      | Error: DownloadError
bionic-tgi-1      | 2023-12-09T11:25:07.121683Z ERROR download: text_generation_launcher: Download encountered an error: Traceback (most recent call last):
bionic-tgi-1      | 
bionic-tgi-1      |   File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
bionic-tgi-1      |     sock = connection.create_connection(
....
....
 urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f44475e3700>: Failed to resolve 'huggingface.co' ([Errno -3] Temporary failure in name resolution)
```

**Comment by ianpurton** [comment]
I'm going to close this out as it's an issue for TGI.

For a production scenario you can have internet access i.e. to download docker images.

It's not as tight as I would like it.
