### ISSUE TITLE
Feature Request - Add Folder for document uploading

### ISSUE THREAD

**Issue by dmerriman11** [bionic-gpt/bionic-gpt#165]
Great work on this project!

Feature request, would it be possible to add folder functionality to supplement the file by file upload?

Adding 100 documents one by one can be tedious for those who don't know how to leverage the document pipeline API.

Thank you for your consideration.

**Comment by ianpurton** [comment]
This is a great idea and actually a small change, this will be available in the next release.

**Comment by ianpurton** [comment]
Fixed in 1.4.10
