### ISSUE TITLE
Can't accept an invitation if not logged in

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#167]
Hello,

the issue of sending mail of yesterday is resolved , thank you 👍 
      INVITE_DOMAIN: http://x.XX.X:7700
      INVITE_FROM_EMAIL_ADDRESS: axxxxxxxx@gmail.com
      SMTP_HOST: smtp-relxxxxxxxxxay.brevo.com
      SMTP_PORT: 587
      SMTP_USERNAME: axxxxxxxxxxxx@gmail.com
      SMTP_PASSWORD: 
      SMTP_TLS_OFF: 'false'

but url of http://xxxxxxxxxx/app/invite/LAvGQkL9/ZAQaT9381fk return : Access to xxxxxxxx was deniedYou don't have authorization to view this page.
HTTP ERROR 403

other issue : resend invite in the user interface not send email not works .

Thank you

**Comment by ianpurton** [comment]
@robertsmaoui Thanks, I'll take a look at this.

**Comment by ianpurton** [comment]
@robertsmaoui So the user that accepts the invitation has to already be registered and logged in.

I realise that's not great as they might not yet be registered or logged in.

But that should get you to the next step at least.

I'll have a think about how best to handle the UI/UX around this.

**Comment by robertsmaoui** [comment]
thank you ianpurton, it’s understood now, 

Please don’t forget to check the second point (resend invite not works)

**Comment by 9876691** [comment]
Will close this based on your other suggestion of skipping email altogether.
