### ISSUE TITLE
How can I download/upload Huggingface models to Bionic?

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#168]
I'd like to have a way through the UI to download models from TheBloke Huggingface and also the ability to upload my own tuned models to Bionic.

Currently it seems I can only use the one 7B that is baked into the install process.

Am I missing something? I'd like to use 13B GGUF models please.

**Comment by ianpurton** [comment]
If the engine you use to run a model supports the Open AI Rest API then you can connect to it with the following instructions. https://bionic-gpt.com/docs/administration/external-api/

An example inference engine you could run is [Local AI](https://localai.io/)

**Comment by ianpurton** [comment]
@tbendien Please let me know this is OK so I can close the ticket.

**Comment by tbendien** [comment]
I'm OK with you closing the ticket. Part of the value of Bionic GPT is the simple install process, UI and UX. Keep in mind that adding a step where users have to run an LLM on another engine and connect with API will significantly complicate the install level of effort, so you will lose a lot of beginner users that want a "click and go" install and use experience.

Also, its a hassle managing multiple pieces of software and API's. Easy enough for developers, not the rest of us.

The opportunity for Bionic is to provide a simple UI that allows the user to load whatever model they want (directly from Hugging Face via url for example) in the same way Text Gen Web UI does.

Then users will then stay with Bionic because its so easy to use. 

Think about rolling out Bionic to 100's or 1000s of end user computers in the field etc. Let's say a worker is going to a place where there is no Internet, . If the install can be done simply and quickly in the field by a "semi technical" person who can that can run a few CLI commands, you are in business!!

Also, think about a user that needs to be able to update a model or configs and then disconnect from the network. 

Then they might want to run different models depending on the use case or the end user needs.

Think simple, quick and easy. Then you dramatically expand your addressable user base beyond highly skilled developers.

Thoughts?

**Comment by ianpurton** [comment]
The install will be simplified in the next couple of days.

1. We've been testing https://ollama.ai/ which we now have working. I can integrate them into our docker compose process.
2. Then there will be a command you can run to download any of the models they support.
3. Integration into the WebUI could happen after that.

Thanks.

**Comment by ianpurton** [comment]
@tbendien I've updated installation docs to give 2 options for GPU setup.

The second is here. https://bionic-gpt.com/docs/running-locally/gpu-setup/
