### ISSUE TITLE
Bug: Setting Prompt Max Tokens to 4096 sends blank message value in API call.

### ISSUE THREAD

**Issue by dmerriman11** [bionic-gpt/bionic-gpt#170]
![2023-12-09 09_12_31-LM Studio](https://github.com/bionic-gpt/bionic-gpt/assets/61134940/834e7fb2-6bde-49ad-97b5-0474bdd4d93b)

But setting it back down to 2048 it will send the proper message value.

![2023-12-09 09_16_47-LM Studio](https://github.com/bionic-gpt/bionic-gpt/assets/61134940/ebe499e8-d115-41aa-a93c-be5f074316cc)

**Comment by ianpurton** [comment]
I think that's expected behaviour. 

We take the context size of the model - max_tokens to be the space we can use for your prompt. The rest of that space is for the LLM's reply.

I've added some documentation here https://bionic-gpt.com/docs/rag/prompt/

**Comment by dmerriman11** [comment]
Thank you for that clarification, I tested it with a 13B and 70B and that seems to be the case.

**Comment by tbendien** [comment]
Hi Ian, I am not seeing the Trim Ratio slider bar on my install of Bionic. Perhaps I need to update the install?

**Comment by ianpurton** [comment]
@tbendien If you can't see it, then yes you need to update. It's on the prompt slideout.
