### ISSUE TITLE
Issue: Multiple file upload - Still restricted to 50mb in total.

### ISSUE THREAD

**Issue by dmerriman11** [bionic-gpt/bionic-gpt#171]
First off, thank you for adding this feature so fast. Brilliant!

I don't know if this is a limitation of the dockers or a bug, so please advise.

The 50mb file striction is being applied to multiple files in total, e.g. if I upload 5, 11mb files, they will not upload. if I reduce it to batches of 4 they get added to the queue and start to process.

So it seems the 50mb per file limitation is being applied to the batch in total as well.

Also, it starts to process all files uploaded

![2023-12-09 13_12_47-LLM Training Data _ Documents - Vivaldi](https://github.com/bionic-gpt/bionic-gpt/assets/61134940/f128aef0-102f-4508-9db5-688af27d70b5)

Not a big issue when it's batches of 4, 11mb files, however, batches of  20 or more I  suspect would be problematic. The ability to set the value of how many it processes concurrently would be helpful.

Also let me know if I can send you a donation for all your hard work.

**Comment by ianpurton** [comment]
@dmerriman11 Thanks, I'm going to look at making this configurable.

The restriction is just there to stop people overloading the system in the situation where there are multiple users.

**Comment by dmerriman11** [comment]
Understood thank you.

**Comment by ianpurton** [comment]
The only restriction appears to be a timeout in the envoy proxy.

https://github.com/bionic-gpt/bionic-gpt/blob/main/.devcontainer/envoy.yaml#L64

Set to 60 seconds. Will investigate some more.
