### ISSUE TITLE
LocalAI model return Error occurred while generating

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#175]
Hello, 
when i used LocalAI in my server , it works without issue : 

 curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{ "model": "llama-2-13b-chat-fp16FR.ggmlv3.q4_K_M.bin",  "messages": [{"role": "user", "content": "BONJOUR, tu vas bien ?"}],  "temperature": 0.7}'
{"created":1702286309,"object":"chat.completion","id":"e53fc92c-c7d8-42f4-b556-2af88e4b0451","model":"llama-2-13b-chat-fp16FR.ggmlv3.q4_K_M.bin","choices":[{"index":0,"finish_reason":"stop","message":{"role":"assistant","content":" Bonjour, je vais bien."}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

but in Bionic-gpt, i created a new model : 

llama-2-13b-chat-fp16FR.ggmlv3.q4_K_M.bin | http://host.docker.internal:8080/v1 | Large Language Model | 13 Billion | 2048

in the prompt , i get this error : Error occurred while generating.

Thank you for help .

**Comment by robertsmaoui** [comment]
Resolved thank you

**Comment by ianpurton** [comment]
Perhaps, as you chat more the context grows as we add more history. How much ram do you have?

**Comment by robertsmaoui** [comment]
RAM
32 GB ECC 2666 MHz

The error occurs also for new chat .

in .env of LocalAI, THREADS=12

**Comment by ianpurton** [comment]
Is this a windows or a linux setup?

One other option is to try our ollama setup https://bionic-gpt.com/docs/running-locally/gpu-setup-ollama/
