### ISSUE TITLE
issue in dev mode anyhow lib

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#181]
Hi,

when i execute wa (https://github.com/bionic-gpt/bionic-gpt/blob/main/CONTRIBUTING.md),

compiling anyhow v1.0.75
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.75/src/lib.rs:214:32
    |
214 | #![cfg_attr(backtrace, feature(error_generic_member_access))]
    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `anyhow` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
[Finished running. Exit status: 101]

**Comment by ianpurton** [comment]
So the CI/CD pipeline is running and it uses the same devcontainer. 

Did you make any changes?

**Comment by robertsmaoui** [comment]
Yes, resolved now , thank you !
