### ISSUE TITLE
Add 2FA TOTP support

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#187]
Do you have plans to add 2FA?

**Comment by ianpurton** [comment]
I've documented how to enable OTP (one time passwords)

https://bionic-gpt.com/docs/production/authentication/

Reopen this if you need more the OTP.

**Comment by tbendien** [comment]
To clarify, I have a customer that needs to have 2FA/MFA availbale on Bionic to meet their security policy. This means that Bionic gives the user the ability to scan a QR code with their Google, Duo or Microsoft authenticator app and then get a 6 digits code that they enter into the Bionic app to authenticate after they enter their user an password. Can you do that? Its widely used, so imagine that you could implement that using Google Authenticator for example?
