### ISSUE TITLE
I've documented how to enable OTP (one time passwords)

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#191]
I've documented how to enable OTP (one time passwords)

https://bionic-gpt.com/docs/production/authentication/

Reopen this if you need more the OTP.

_Originally posted by @ianpurton in https://github.com/bionic-gpt/bionic-gpt/issues/187#issuecomment-1855319916_

**Comment by ianpurton** [comment]
Here's my position

Attacker has access to the users email account.

1. Goes to login
1.  Attacker is challenged by TOTP
1. Attacker select "Login in an alternative way"
1. Attacker selects verification by email
1. We send OTP

I think TOTP is not more secure than OTP. 

I don't know how to implement TOTP without an email fallback.
