### ISSUE TITLE
Multi level Role Based Access

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#197]
I have customers that have small workgroups e.g.5 to 50 users, that will not use SSO or a third party authentication service.

I plan to deploy a private server for small organizations and then having them connect to it via Cloudflare or local network. That way the users can access Bionic as a simple web service with user/password and Cloudflare will add an SSL cert so the connection will be encrypted.

Would you be able to build the Simple non developer UI for end users that are not developers?

The idea is to build a dedicated private AI server for a single client with several users.
The client understands that performance will vary depending on use of the server.

Is it possible for you to provide a way in the admin UI to add a “user” stripped down UI so that that basic users don’t get confused and try to changes things?

For example for use cases like creative writers, we would educate them on how to set/use history, temperature etc
For creative types, those types of features will be important.
I will educate them on the limits of tokens consumed via long prompts which then blow out token limits etc.

A low RBAC level “User” would have simple rights, not able to build Teams etc.
Also, I want to be able to bulk upload users, define their roles and have Bionic send them an email invitation.

The things I suggest to be removed for a simple low level user UI would be access to:

LLM API keys
Sysadmin section
Ability to see audit trails - thats for sysadmin only - in future a level 1, 2, 3, 4 role hierarchy would be outstanding.
It should be possible to name the roles as needed so it is easy to see which user has which level of access, or, to assign RBAC access level to a username by the sysadmin.

If you can build in multi level RBAC, it will make it super fast and easy to deploy and use out of the box vs having to deploy SSO for small workgroups and then I can build an MSP business around the software out of the box!

**Comment by tbendien** [comment]
It is also important for individual users to be able to download their own chat history directly from the UI if possible vs having to set up another app that talks to the database.

**Comment by tbendien** [comment]
In future, querying the database would be used for audits, analytics on what the users are doing, connecting to event logging tools with dashboards which can alert sysadmins or managers to inappropriate prompts or problems.

**Comment by tbendien** [comment]
https://bionic-gpt.com/docs/administration/roles/

The problem with users being able to create their own teams without central control is that this can put load on the private GPU server in an uncontrolled manner. This then drives cost impact as the organization who is funding the server (central IT or line of business) suddenly gets a system performance hit as new users are added and then start driving load on the server.

There needs to be centralized control of the users on the server so that total users and roles can be managed. Just like any enterprise application. Then the sysadmin can monitor overall load on the server and determine which users are driving excessive consumption, put load balancing in front of a cluster of servers or put in bigger servers.

Does that make sense?

**Comment by ianpurton** [comment]
@tbendien Yes. Understood.

**Comment by ianpurton** [comment]
> It is also important for individual users to be able to download their own chat history directly from the UI if possible vs having to set up another app that talks to the database.

Please raise as a separate issue so I can track everything better.
