### ISSUE TITLE
Error occurred while generating.

### ISSUE THREAD

**Issue by 3x3cut0r** [bionic-gpt/bionic-gpt#199]
I started the docker-compose.yml from this repo withouth modifications on my Mac Mini M2.
All containers started without errors and are running, except the migrations-1 container, which should be normal.
I registered a new account.
If i enter a prompt in the Chat Console i get: `Error occurred while generating.` inside the chat window.
The docker log from the app-1 container says:
`ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error trying to connect: tcp connect error: Connection refused (os error 111)"`
The log from the llm-api-1 is completely empty.

Am i something missing?

**Comment by ianpurton** [comment]
I take it your using the ollama setup? https://bionic-gpt.com/docs/running-locally/gpu-setup-ollama/

Assuming you are, then the llm-api shoud contain something. i.e. the logs of the litellm proxy https://docs.litellm.ai/docs/proxy/deploy

Perhaps you could run litellm on it's own to check it works?

**Comment by 3x3cut0r** [comment]
I followed the normal CPU setup: https://bionic-gpt.com/docs/running-locally/docker-compose/
Is this not working out of the box?

**Comment by ianpurton** [comment]
> I followed the normal CPU setup: https://bionic-gpt.com/docs/running-locally/docker-compose/ Is this not working out of the box?

You should follow this https://bionic-gpt.com/docs/running-locally/apple-silicon/

The page title is "Apple Mac (Arm)" is there a better way for me to phrase that as I would hope you would have spooted it.

**Comment by 3x3cut0r** [comment]
yeah i spotted it. but i only want to test this setup on my mac. i will deploy it later on a linux machine. so i want to get it running without ollama and just want to run one docker stack.

**Comment by ianpurton** [comment]
@3x3cut0r We may integrate the ollama into the one docker stack at some point.

I'll close this out as it's a know issue. The model we use in the one docke stack doesn't work on apple silicon.
