### ISSUE TITLE
Role based user chat history push to local or external storage

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#200]
Users should be able to download their chat history (prompts and repsonses) per chat session based on role.
For example:

Sysadmin - able to download chat history from all users based on time range, per user.
Team manager: able to download chat history from an individual on their team or all teams over a given date range
End user: be able to download their chat history over a given time range.

Obviously chat history can quickly balloon out, so a chat retention policy must be set by the sysadmin on a per user, team or overall system requirement.

If local storage in the private server is used, the sysadmin could put in a large SSD to capture chat logs if there is no long term history rentention requirement.

An option to push chat history to a persistent storage end point like an NFS volume or S3 object or Minio storage bucket would be ideal. Then sysadmins can use other tools to query chat history in the object storage.

Then the chat history can be retained based on regulations as needed, including GDPR, local laws etc. In some cases, chat history might need to be kept for several years for legal audit or law enforcement investigations etc.

Chat history also provides valuable data sets that can be used for finetuning and other analysis.

Net net, being able to offload chat history to an archive storage target is a key value add and requirement for Bionic if you can make it easy to use!!!

**Comment by ianpurton** [comment]
Chat history offloading etc is out side the scope of Bionic.

That's because it's all relatively easy to implement as a cronjob or postgres job and everyone might have a different idea what they want to do.

i.e. ask Chat GPT "Write a postgres job to archive a chat table to s3" and see what it does.

Download chat is another issue on here already I think.
