### ISSUE TITLE
Multiple user sessions permitted with the same email

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#201]
I believe there should be only one session allowed per email that is logged into Bionic?

**Comment by ianpurton** [comment]
Here's what I have

**Comment by tbendien** [comment]
Let's say that you have a customer who has a sensitive data set that they are working with. They log into a session and then walk over to another computer and log in. 

They forget to log out of the first computer and someone walks up and sees their browser open and looks at the tab the use was working on and then sees the sensitive data. That's a security risk. 

Any computer that is logged into an application that has access to sensitive data (which is why the organization is using private GPT applications) should not permit multiple sessions and the sessions should also automatically log out after a period of inactivity, lets say 10 to 30 minutes.

 Just like your bank web access, it automatically logs you out (in my case after 10 minutes) of inactivity.
