### ISSUE TITLE
Updating Bionic without deleting the database?

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#202]
In the instructions on https://bionic-gpt.com/docs/running-locally/gpu-setup/

It recommends running the command below to do the upgrade which will delete the entire database.
I'd like to do Bionic upgrades without losing all my custom prompt settings and datasets.
What is the best way to upgrade Bionic and preserve my database?

**Upgrading to a later version of BionicGPT**
When upgrading to the latest version of BionicGPT we recommend running

docker-compose -f docker-compose.yml -f docker-compose-gpu.yml down -v
_to completely delete the database._

**Comment by ianpurton** [comment]
You don't need to do that anymore. I'll update the docs.
