### ISSUE TITLE
[INFORMATION REQUEST] Forward with NGINX/SWAG

### ISSUE THREAD

**Issue by eyalspier** [bionic-gpt/bionic-gpt#213]
This is a fantastically powerful tool, and would perfectly fit the use case I have. If I would want to proxy this e.g. via nginx, I would only have to forward the envoy container port, is this correct? Do you have any documentation regarding this? I couldn't find it in the docs!

**Comment by ianpurton** [comment]
We don't have docs for nginx, but you are correct forwarding the envoy port is sufficient

**Comment by eyalspier** [comment]
Many thanks. I will attempt this and raise an issue in case of any unforseen problems.
