### ISSUE TITLE
[FEATURE REQUEST] Persistent Volumes on docker compose

### ISSUE THREAD

**Issue by eyalspier** [bionic-gpt/bionic-gpt#215]
I cannot seem to get the dockerized version to persist the data. Where can volumes be assigned so that the data remains after a restart? This would be a very useful feature as it would ensure stability throughout maintenance cycles.

**Comment by ianpurton** [comment]
That's unusual, the data is normally there after a docker compose restart.

What commands did you run?

**Comment by eyalspier** [comment]
I just ran docker-compose down, followed by docker-compose up -d. My user account is gone, as well as the previously added documents. Any ideas how to persist the information?

**Comment by ianpurton** [comment]
On my system docker compose up/down will not erase the data.

However,  you may want to try this. https://stackoverflow.com/questions/42107364/how-to-use-volume-in-docker-compose-for-postgres

**Comment by ianpurton** [comment]
Closing, I don't think this is a Bionic issue.
