### ISSUE TITLE
Add the PGadmin yaml to the repo

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#237]
Could you put the pgadmin yaml to the repo so people can start using the Postgres for running reports please?

Here is the yaml with the default values that we built:

docker-compose-pgadmin.yml 

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgadmin-data:

**Comment by ianpurton** [comment]
I don't want to collect up to many docker yaml in the repo. 

Eventually I will get down to 1 docker-compose hopefully.

The plugin is documented.
