### ISSUE TITLE
Chats table appears to be truncating full response in the chats table

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#241]
I need to be able to audit the full prompt and responses that users are creating in the postgres DB.
This is for end user policy compliance and other situations where a usage on a private system needs to be analyzed for trends etc.

The response seems to be getting cut off. It appears to be happening after the response has a colon eg:

I will do more testing, but is there a character limit on how many characters are written to postgres for the response column?

**Comment by tbendien** [comment]
So I just asked Claude and he said the following. It makes sense, the issue is that I need the whole prompt response for auditing. So perhaps its a case of editing the prompt template or something like that? Any Pro Tips welcomed!

A colon can cause response logs to be truncated when writing to a Postgres database due to how Postgres handles the COPY command.

Specifically:

The COPY command is often used to bulk load data into Postgres tables from CSV files
By default, COPY treats the colon (:) character as a column delimiter, similar to a comma
So if a log entry contains a colon within its values, Postgres will think that colon is a new column delimiter
This causes the remaining text after the colon to be interpreted as a new column
So the original log value gets truncated at the colon character

**Comment by ianpurton** [comment]
Do you mane we are not storing all the response, or you're having an issue extracting data?

Please provide a screenshot so we can see what you are doing.

**Comment by tbendien** [comment]
Actually, when I exported the report output, it did show the entire response. I was looking at the PGadmin UI and the format of the columns did not show me the full result. My mistake, so ticket closed. I will post the yaml that I am using and SQL in the Discussions as it is very useful to run the reports for chat history. Thanks all!
