### ISSUE TITLE
Can't find local ollama models 

### ISSUE THREAD

**Issue by jakbin** [bionic-gpt/bionic-gpt#245]
I follow this https://bionic-gpt.com/docs/running-locally/gpu-setup-ollama/ tutorial , but can't find my local ollama models , that I have pulled using ollama command . 

Please provide a option to select model by users choice .

**Comment by tbendien** [comment]
Hi there, try this procedure:

Start Bionic with the standard docker-compose.yml file.
Add the GPU yaml if you have a GPU docker-compose-gpu.yml

You have to modify the docker-compose-ollama.yml file to include the model you want to use and then run a command that is shown below.

Modify the yaml:

nano docker-compose-ollama.yml 

You can only use models from Ollama which are here: https://ollama.ai/library

Then to download and run the model from Ollama you need to use this command, in this case, for a llama2:7b model found at: https://ollama.ai/library/llama2/tags

use the part of the tag from Ollama in the window that says (in this case) "ollama run llama2:7b"

You can see the complete command here that you have to run at the CLI after you modify the docker-compose-ollama.yml  file (FYI I use Ubuntu):

After you modify the yaml file, run it:

docker-compose -f docker-compose-ollama.yml 

Then run:

docker exec -it bionic_ollama_1 ollama run llama2:7b

Here is an example of the yaml for the 7B model - look for the two lines that say "model ollama/llama2:7b" and replace that with the model tags from the Ollama webpage for the model you want:

    command: ["/bin/sh", "-c", "pip install async_generator && litellm --model ollama/llama2:7b --api_base 

gtadmin@gtaiquadgpu:~/bionic$ cat docker-compose-ollama.yml
services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
#insert number of GPU’s in use
              count: 1 
              capabilities: [gpu]
  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command: ["/bin/sh", "-c", "pip install async_generator && litellm --model ollama/llama2:7b --api_base http://ollama:11434 --host 0.0.0.0 --port 3000"]
    entrypoint: []
    platform: linux/amd64
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

**Comment by bdurrani** [comment]
@tbendien 
Do we need any additional steps to get the model to show up on the UI?

Also, looks like you end up pulling the model in the `ollama` container and trying to use that vs. using the one installed on the host? Is that correct?

**Comment by tbendien** [comment]
The model won't show up on the UI at the moment. 
Yes, you will be using the model running in the Ollama container. Bionic will connect to that container and use that for the prompts.

Once you run the docker-compose -f docker-compose-ollama.yml command, you should see the >>> prompt where you can test to see how the model is running.

Are you running with a GPU on Linux?

**Comment by jakbin** [comment]
Why bionic gpt don't use ollama api to find all availables local model , and then show it on webui ??

Just like ollama-webui .

**Comment by tbendien** [comment]
Good idea, suggest you put this suggestion into the Ideas section:
https://github.com/bionic-gpt/bionic-gpt/discussions/categories/ideas

@ianpurton @kulbinderdio

**Comment by bdurrani** [comment]
> The model won't show up on the UI at the moment. Yes, you will be using the model running in the Ollama container. Bionic will connect to that container and use that for the prompts.
> 
> Once you run the docker-compose -f docker-compose-ollama.yml command, you should see the >>> prompt where you can test to see how the model is running.
> 
> Are you running with a GPU on Linux?

Running on Mac M1, OS 14.x.

**Comment by bdurrani** [comment]
I think I got it working using the local version of ollama

I updated the model and updated `api_base` to point to the host ip in the docker compose file

```shell
"pip install async_generator && litellm --model ollama/llama2:13b --api_base http://host.docker.internal:11434 --port 3000"
```

The ollama docker compose file now looks like this

```yaml
services:
  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command:
      [
        "/bin/sh",
        "-c",
        "pip install async_generator && litellm --model ollama/llama2:13b --api_base http://host.docker.internal:11434 --port 3000",
      ]
    entrypoint: []
    platform: linux/amd64
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

I managed to skip the step of installing the model in the container.

**Comment by tbendien** [comment]
Glad you got it working! What type/size GPU are you running?

**Comment by bdurrani** [comment]
> Glad you got it working! What type/size GPU are you running?

Just whatever is built in with the Mac Pro M1. Not sure how much memory it has.

I think with the above configuration, I managed to get the chat functionality working, but it messed up the  document pipeline embedding extraction.

**Comment by ianpurton** [comment]
Closing out please reopen if there are further issues.
