### ISSUE TITLE
empty response in chat

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#250]
the chat was working correctly (using ollama), but accidentally it returns an empty response, I check the docker logs: 

  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 277, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 707, in async_data_generator
    async for chunk in response:
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 204, in _async_streaming
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4634, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4501, in exception_type
    raise ServiceUnavailableError(
  File "/usr/local/lib/python3.9/site-packages/litellm/exceptions.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.9/site-packages/openai/_exceptions.py", line 79, in __init__
    super().__init__(message, response.request, body=body)
AttributeError: 'NoneType' object has no attribute 'request'

**Comment by ianpurton** [comment]
Can you give me some more context? i.e. what steps to follow to reproduce this?

**Comment by robertsmaoui** [comment]
I sent a message which generated a long response, I did not receive the full response, it was cut off.
So I decided to increase the context window from 2048 TO 4096 so I did another test, I received error occured.
then I reinstalled ollama and ran docker ollama, the response became completely empty.

Now I reinstalled everything. It's solved but I lost the data.
Is there a version of docker compose file that we can use in case of a problem without reinstalling the database or other solution ?

**Comment by robertsmaoui** [comment]
Hello @ianpurton , i get the error : "Error occurred while generating" in chat console (long history chat). after that i started a new chat with other model, and the error "Error occurred while generating" occurs , logs in llm-api container :

Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"
thread 'tokio-runtime-worker' panicked at /usr/src/cria/src/inferer.rs:185:13:
Can't append the event on inference queue. Err "sending on a closed channel"

please find a solution for that because i think this issue is for many users

**Comment by ianpurton** [comment]
@robertsmaoui Are you still getting this issue?

Also we now have some config to get a jupyter notebook running https://bionic-gpt.com/docs/administration/jupyter-notebook/

This may help reproduce the issue.
