### ISSUE TITLE
Couldn't deploy on OpenShift due to permission denied for embeddings pod

### ISSUE THREAD

**Issue by jeremyssc** [bionic-gpt/bionic-gpt#256]
Hello,
I have tried to deploy your project on an OpenShift cluster, but the pods seem to be waiting on the embeddings pod which is in an error state and is in a crash loop. 

Here are the logs for the embeddings pod:
```
{"timestamp":"2023-12-27T18:24:29.438912Z","level":"INFO","message":"Args { model_id: \"BAAI/bge-small-en-v1.5\", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, hf_api_token: None, hostname: \"embeddings-7cc64cfc89-zb5tr\", port: 80, uds_path: \"/tmp/text-embeddings-inference-server\", huggingface_hub_cache: Some(\"/data\"), json_output: true, otlp_endpoint: None, cors_allow_origin: None }","target":"text_embeddings_router","filename":"router/src/main.rs","line_number":149}
{"timestamp":"2023-12-27T18:24:29.438984Z","level":"INFO","message":"Token file not found \"/.cache/huggingface/token\"","log.target":"hf_hub","log.module_path":"hf_hub","log.file":"/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hf-hub-0.3.2/src/lib.rs","log.line":55,"target":"hf_hub","filename":"/usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/hf-hub-0.3.2/src/lib.rs","line_number":55}
Error: The `--pooling` arg is not set and we could not find a pooling configuration (`1_Pooling/config.json`) for this model.

Caused by:
    0: I/O error Permission denied (os error 13)
    1: Permission denied (os error 13)

```
I haven't seen any issues like this in this repo so I just wanted to give you a heads up that I encountered this error.
I am running OpenShift 4.14.6 if it helps. 

You will find the log file for the embeddings pod as well as the Pulumi file I used below . 

[embeddings-7cc64cfc89-zb5tr-embeddings.log](https://github.com/bionic-gpt/bionic-gpt/files/13780561/embeddings-7cc64cfc89-zb5tr-embeddings.log)
[Pulumi.yaml.txt](https://github.com/bionic-gpt/bionic-gpt/files/13780605/Pulumi.yaml.txt)

Thanks,
Jeremy

**Comment by ianpurton** [comment]
@jeremyssc We'll get a fix for this soon as a later version of LLMLite doesn't need this fix. Just need to test it first.

**Comment by ianpurton** [comment]
@jeremyssc Could this be that the embeddings container is trying to download the model and gets blocked?

**Comment by jeremyssc** [comment]
> @jeremyssc Could this be that the embeddings container is trying to download the model and gets blocked?
I don't know is there commands that I can do to determine that ?

**Comment by ianpurton** [comment]
I'm now able to reproduce this issue with the following

`docker-compose -f docker-compose.yml -f docker-compose-hardened.yml up`

Embeddings API is trying to access hugging face despite having the model already loaded.

**Comment by tbendien** [comment]
yep, this is the kind of issue I am seeing also. Would be ideal if Bionic can run fully air gapped once all the containers and models are fully installed :-) Use cases are for stand alone systems that are to be used in environments where there is no internet eg remote areas, secure facilities where there is no outside network access etc
