### ISSUE TITLE
access and visibility

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#257]
There are things that don't work regarding viewing and authorization rights:
1. You said that only the first registered user is the system administrator who is authorized to create models, while other users can also

2 When I create a prompt and make it visible to the entire company, we don't see it for other users

3 when we create a dataset in a team A and invite a new user to this team, the invited user when he creates his team B, he sees the dataset despite switching to his team B, normally he should not see it

**Comment by robertsmaoui** [comment]
Excuse me , i don't test latest version yet !

**Comment by robertsmaoui** [comment]
1 is resolved with in the latest version
2 
![prompt1](https://github.com/bionic-gpt/bionic-gpt/assets/2206468/d07a51bf-8289-4d41-9337-d0d8f96d2189)

![prompt2](https://github.com/bionic-gpt/bionic-gpt/assets/2206468/82456d87-e1b0-4573-b8c1-b2abc55e931d)
 3 not works also !

other issue : reset password error : error returned from database: column "reset_password_sent_at" of relation "users" does not exist

**Comment by ianpurton** [comment]
@robertsmaoui Thanks, we'll get onto this soon.

**Comment by robertsmaoui** [comment]
@ianpurton just a reminder, thanks !
