### ISSUE TITLE
Unable customise the entire UI

### ISSUE THREAD

**Issue by martian-coder** [bionic-gpt/bionic-gpt#262]
Please provide me code details as I was able to build the and run the app but unable to customise th ui. 

Where is the actual ui code that I can modify.

I have downloaded the entire  bionicgpt as raw-gituser link is blocked for me.  So I ran docker compose I local folder. But now how to customise the ui. I see multiple folders with ui as the name but no idea which is which.

Can you guide me through as I m really curious to get this customised.

**Comment by ianpurton** [comment]
The UI is implemented with Dioxus https://dioxuslabs.com/
