### ISSUE TITLE
logout issue v.1.5.1

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#266]
Hello,

logout not works in new version, 

and it is possible to use first name and last name in the registration form in the user profile.

thanks

**Comment by ianpurton** [comment]
Yes, I have some work to do related to this. https://github.com/oauth2-proxy/oauth2-proxy/issues/2372

Thanks for trying it out so quick, this is the Open ID Connect integration release.

**Comment by robertsmaoui** [comment]
Hello @ianpurton , please, i want to know the advantage and usefulness of using Open ID in bionic ?

**Comment by ianpurton** [comment]
@robertsmaoui Bionic is designed to be installed in enterprises and often they have single sign on.
