### ISSUE TITLE
Request: Recommendations for proper prompt usage & testing response quality.

### ISSUE THREAD

**Issue by bigbeef105** [bionic-gpt/bionic-gpt#272]
**Here is an example of testing I have done, and I would like some guidance.**

Upload XLSX with this record: (one of first rows of ~3,000)
<img width="560" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/10541294/f4214c8a-c467-465f-9024-80b1fde16c0b">

**After processing completed, I submitted the below and got this response:**

<img width="684" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/10541294/b2067585-c3a6-4f0d-b047-fc9d486bbd0b">

I then copied this record and pasted it into a word document to ensure a formatting glitch wasn't preventing unstructured from handling it correctly.  After uploading the word document, allowing processing to complete, and submitting the prompt in a new chat, I got the same response.

**My Prompt:**

<img width="400" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/10541294/9d5ad938-e108-4828-a094-dbb313ff1c23">
<img width="400" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/10541294/25ed195b-a691-4802-ab64-0a94876a6cf7">

**My Model:** (Actually Mixtral, Just haven't updated the model name in the description field)

<img width="400" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/10541294/2c432985-9304-496f-babc-87cabae5ca8d">

**Comment by ianpurton** [comment]
Can you click on the "View Prompt" and show whats in the prompt. This is what gets sent to the LLM.

Thanks.

**Comment by bigbeef105** [comment]
Full Prompt
[X](http://localhost:7800/app/team/1/console/25#)
[
	{
		"role": "system",
		"content": "Context information is below.\n--------------------\n{-07-17 [GB2570240]\\nGB201906015         D0 2019-06-12 [GB201906015]\\nJP6831213           B2 2021-02-17 [JP6831213]\\nJP2018075191        A  2018-05-17 [JP2018075191]\\nCN109922702         B  2021-07-09 [CN109922702B]\\nCN109922702         A  2019-06-21 [CN109922702]\\nTWI653965           B  2019-03-21 [TWI653965]\\nTW201817361         A  2018-05-16 [TW201817361]\n79740545\n2017-06-07\n2019-08-22\nGranted Alive\n\n\n2475\nUS20210059493A1\nVacuum cleaner\nA vacuum cleaner includes a main casing, driving wheels, a cleaning unit, a memory, a sensor part and a communication part, a discriminating part, and a travel control part. The memory stores map data. The sensor part and the communication part acquire the information on a plurality of cleaning areas from an outside. The discriminating part discriminates the plurality of cleaning areas from the map data stored in the memory, on the basis of the information acquired by the sensor part and the communication part. The travel control part controls the driving of the driving wheels to make the main casing autonomously travel in each of the cleaning areas discriminated by the discriminating part. The vacuum can perform smart cleaning operation appealing to a user.\nNavigation\nUser Comfort\nTo improve user experience\nTo perform smart cleaning operation appealing to a user\nOn the other hand, the generated map data includes the entire cleaning area, and is not suitable for recognition of individual rooms in the cleaning area. Therefore, the vacuum clea\nvalues of the plurality of identified parameters.\n12. The method of claim 9,   wherein the obtaining driving result data comprises:   simulating driving of the external electronic apparatus on the obtained map based on a plurality of parameter sets respectively including a plurality of parameter values, and obtaining driving result data for each parameter set, and training the artificial intelligence model based on the plurality of parameter sets and the obtained driving result data and obtaining a plurality of parameter values related to driving of the external electronic apparatus, and   wherein the plurality of parameter sets include a first parameter set and a second parameter set wherein parameter values of at least one parameter are different.\n13. The method of claim 12,   wherein the artificial intelligence model includes a plurality of neural network layers, and   in the plurality of neural network layers, weights included in each of the plurality of neural network layers are trained based on the plurality of parameter sets and driving result data obtained for each of the plurality of parameter sets, and   wherein the obtaining the plurality of parameter values comprises:   obtaining a plurality of parameter values related to driving of the external electronic apparatus from an input layer among the plurality of neural network layers based on the weights being trained.\n14. The method of claim 9,   wherein the driving result data includes at least one of a size of an a\n311725T]\\nDK3311723           T3 2020-12-21 [DK3311723T]\\nCN106455897         B  2020-03-10 [CN106455897B]\\nCN106455897         A8 2017-06-30 [CN106455897]\\nCN106455897         A  2017-02-22 [CN106455897]\\nES2742217           T3 2020-02-13 [ES2742217]\\nDK3311724           T3 2019-08-12 [DK3311724T]\\nAU2017265156        B2 2018-11-22 [AU2017265156]\\nAU2017265154        B2 2018-11-22 [AU2017265154]\\nAU2017265153        B2 2018-11-22 [AU2017265153]\\nAU2017265151        B2 2018-11-22 [AU2017265151]\\nAU2017265156        A1 2017-12-14 [AU2017265156]\\nAU2017265154        A1 2017-12-14 [AU2017265154]\\nAU2017265153        A1 2017-12-14 [AU2017265153]\\nAU2017265151        A1 2017-12-14 [AU2017265151]\\nAU2015229486        B2 2017-12-07 [AU2015229486]\\nAU2015229486        A1 2016-09-15 [AU2015229486]\n45947636\n2013-03-05\n2016-06-28\nGranted Alive\n\n\n1648\nUS20210401255A1\nArtificial intelligence robot and method of operating the same\nAn artificial intelligence robot includes a camera configured to acquire image data, a memory configured to store an object recognition model used to recognize an object from the image data, and a processor configured to acquire a speech command, determine whether an intention of the acquired speech command is object search, recognize an object from the image data based on the object recognition model during traveling when the intention of object search, and output a notification indicating that the object has been recognized when the recognized object is an inte\n017-01-16 [TW201702780]\\nES2744749           T3 2020-02-26 [ES2744749]\\nCN107592922         A  2018-01-16 [CN107592922]\\nSG11201707997V      A  2017-10-30 [SG11201707997V]\n74338392\n2016-04-04\n2019-10-29\nGranted Alive\n\n\n2599\nUS11269350B2\nMethod for creating an environment map for a processing unit\nA method for creating an environment map for a processing unit, which moves independently within an environment, wherein a detection device detects environmental features and/or objects within the environment, and wherein position data of the environmental features and/or objects are processed by an evaluation device into an environment map. In order to achieve intuitive user-processing unit interaction, the detected environmental features and/or objects are processed via 3D reconstruction into a photo-realistic, three-dimensional environment card.\nNavigation\nMap Generation\nNeed to generate or update maps\nTo generate map of the room, easier to read for user\nEven though an environment map can be generated with the known method, it is in part difficult for a user to read. This is because the environment of the processing device is often displayed as a 2D grid map. This grid map is a very simplified, schematic depiction of the environment, and resembles a floor plan of a room. The latter typically exclusively contains information recorded within a horizontal detection plane corresponding to the working height of the processing device, and also does not distinguish between environment fe\n}\n--------------------"
	},
	{
		"role": "user",
		"content": "is WO2022004949A1 in the dataset?\n"
	}
]

**Comment by ianpurton** [comment]
@bigbeef105 Thanks, we'll take a look at this.

**Comment by kulbinderdio** [comment]
@bigbeef105 there is still a lot of work underway in regards to RAG and tabular data.

Some of the research done has found converting these files into HTML and then using them in RAG systems produces better results. While it may not be what you're after as an end goal are you able to test this with your data and see if you get anything closer to what you would expect?

I did a quick test where I created the a very small doc with the information shown above.
I lowered the temperature associated with the prompt to 0.1 and get the following result

![image](https://github.com/bionic-gpt/bionic-gpt/assets/4700433/a92789a0-7eb9-458d-b4fb-58bced4cf828)

**Comment by kulbinderdio** [comment]
Some of the other research also revolves around the embedding model used and the embedding dimensions.
While I did not change the embedding model for the results above, bionicGPT is built so you can use other embedding tokeniser with different dimension vectors.

Here is an exmaple of a file called docker-compose-embed-gpu.yml
```
services:
  embeddings-api:
    image: ghcr.io/huggingface/text-embeddings-inference:0.2.2
    platform: linux/amd64
    command: --model-id intfloat/e5-large-v2 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

Not only is this faster as embeddings are performed on the GPU but the model specified ranks much higher in HuggingFaces MTEB leaderboard (https://huggingface.co/spaces/mteb/leaderboard)

We have only tested on a very limited number of these available mappings

**Comment by kulbinderdio** [comment]
and this is the output when using same html file and Statling-LM-7B-alhpa-AWQ model

![image](https://github.com/bionic-gpt/bionic-gpt/assets/4700433/a1d858c4-6243-4660-b998-9f9b7b51dd67)

**Comment by bigbeef105** [comment]
This looks promising.  Let me experiment with the HTML method as a first step.

**Comment by bigbeef105** [comment]
I added an HTML file with the first 25 rows of the dataset, and processing completed without any issues.  However, the query still returns a negative response.  At this point, I would venture that the RAG has so much data from the prior imports that it still not finding the relevant information to inject.
