### ISSUE TITLE
New docker-compose file has networking issue - not allowing browser access via IP

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#273]
After installing Bionic with the new docker-compose-gpu file, there is an issue where trying to access the host via it's IP address does not work.

Bionic can be accessed via localhost:7800 on the host itself, but not at all with it's local IP, even from the Bionic host itself.

Here is the error message that is shown in the browser when trying to access Bionic from the localhost or remote host in the same subnet:

Enter the IP of the Bionic host: 10.32.1.94:7800

Error message:

http://localhost:7810/realms/bionic-gpt/protocol/openid-connect/auth?approval_prompt=force&client_id=bionic-gpt&redirect_uri=http%3A%2F%2Flocalhost%3A7800%2Foauth2%2Fcallback&response_type=code&scope=openid+email+profile&state=DbaPebfIJ0Mu2eBgLo3SBCh-JBn21lUI7-Idz7JQNsU%3A%2Fauth%2Fsign_in

Logs from the Bionic host:
oauth2-proxy_1    | [2024/01/01 17:06:03] [oauthproxy.go:970] No valid authentication in request. Initiating login.
oauth2-proxy_1    | 10.32.1.47:60608 - 9377fe92-7657-4860-a601-1e9187d8fd43 - - [2024/01/01 17:06:03] 10.32.1.94:7800 GET - "/auth/sign_in" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 302 333 0.000

**Comment by djmaze** [comment]
Yeah, the envoy configuration is broken. It does not contain any upstream auth cluster anymore.

**Comment by ianpurton** [comment]
> Yeah, the envoy configuration is broken. It does not contain any upstream auth cluster anymore.

We've replaced the authentication mechanism with open id connect. In this case we package keycloak as an example provieder.

If you're having issues can you let us know?

**Comment by ianpurton** [comment]
Will close this out as it is the expected behaviour.
