### ISSUE TITLE
 How to run docker-compose file using OpenAI endpoint compatible i.e. OpenRouter on bionic GPT

### ISSUE THREAD

**Issue by syaikhipin** [bionic-gpt/bionic-gpt#274]
Description: I'm having trouble running a docker-compose file using OpenAI endpoint compatible i.e. OpenRouter on bionic GPT. I've tried both the OpenAI and OpenAI-GPT endpoints, but neither seems to work. I'm not sure if there's a configuration issue or if there's something else I need to do.

Steps to reproduce:

Clone the repo
Run docker-compose up -d
Expected behavior:

The OpenAI endpoint should be reachable and the OpenRouter should be running.

Actual behavior:

The OpenAI endpoint is not reachable and the OpenRouter is not running.

Additional details:

I'm running the latest version of Docker and Docker Compose. I'm also running Ubuntu 22.04.

Reproducible:

The issue can be reproduced consistently.

Possible solutions:

Could you please provide some guidance on how to run the docker-compose file using the OpenAI endpoint compatible i.e. OpenRouter on bionic GPT? I'm open to trying any solutions that you recommend.

I would also appreciate it if you could let me know if there are any other docker-compose configurations that I could try.

Thank you for your help!

**Comment by ianpurton** [comment]
Can you show a screenshot of your model setup?

**Comment by syaikhipin** [comment]
![image](https://github.com/bionic-gpt/bionic-gpt/assets/1263409/a2c03c2f-58e7-4aec-9b22-2c1b545508b7)
This is the screenshot, however, I have some error while generating response

**Comment by ianpurton** [comment]
Can you reach the endpoint with curl i.e.

```
curl https://llm-model.onrender.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: YOUR KEY" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'
```

**Comment by syaikhipin** [comment]
Sure, it gives the response, just try it : curl https://llm-model.onrender.com/chat/completions \                              
-H "Content-Type: application/json" \
-H "Authorization: Bearer 1234" \
-d '{
"model": "general1",
"messages": [
{"role": "user", "content": "What is the meaning of life?"}
]
}'

**Comment by ianpurton** [comment]
The config looks correct to me, do you get anything in the log files?

**Comment by syaikhipin** [comment]
Sorry just reply it yet, i try to access docker logs it shows like this : response="status = 422 Unprocessable Entity, message = error trying to connect: dns error: failed to lookup address information: Name does not resolve"

I don't know which part to fix
