### ISSUE TITLE
GPU option not working as expected

### ISSUE THREAD

**Issue by EmmaWebGH** [bionic-gpt/bionic-gpt#275]
Hi
I have 2x 4090s so would like to run fast, larger models.

Not sure if I am missing something here.
Followed the instructions for GPU setup with TGI. That is to say, I did what is said here: `https://bionic-gpt.com/docs/running-locally/gpu-setup/`

   Steps:

Pulled the 2 yamls and and ran
`docker-compose -f docker-compose.yml -f docker-compose-gpu.yml up`

Got the UI up OK, it asked me to sign in. I set a username and pass, at which point I got a black screen with some error about the db.
Refreshed the UI, it came back. This time it said "log in", rather than "sign up". Using the name/pass I just set, I got in.
Front-end loads.

Go to "Model Setup".
How do I use GPU models with TGI here?

Did the ymls above, install what I needed, or it just runs Bionic expecting to see a prior installation of TGI running, that I had installed earlier? Because I didn't. The instructions didn't say I needed that.

When I click "Add Model" it wants me to input an API URL, but what is this? Is Bionic running it's own install of TGI in the background? 
If so, where would it tell me what the API URL for TGI is?
Scrolled around in terminal (running this on win11 so terminal = powershell) but couldn't see anything about an API url forTGI.

Main question is, am I missing part of the install or config? As the install docs are literally just pulling 2 ymls and running docker compose for them.

I can see it has auto-downloaded models--TheBloke--zephyr-7B-beta-AWQ, is that a sign that the GPU yml is working OK?
Cool, but how do you get this to show up in the model selection, and use it?

I wondered if we could just put any GPU model (like a 13b GPTQ model) in the models folder?
But if that's so, it's not seeing the zephyr model it just downloaded.

Apologies, I am confused. :) 

Anyway, it seems to work with CPU? By which I mean, it's answering me with the default 7b it comes with (not zephyr?).

Hope someone can point me in the right direction.
Thanks!

**Comment by tbendien** [comment]
Hi Emma, you can use your two GPU's, you have to set the GPU count to "2" in the docker-compose-gpu.yml file.

However, I strongly recommend that you run Bionic on Ubuntu Linux with a desktop like Gnome.
Running on Windows will likely be problematic and less stable. I am running Bionic on Ubuntu and have it working.

See my runbook for Ubuntu assuming you have a clean fresh install of Ubuntu:
https://gtcyberlabs.org/f/install-bionic-gpt-on-an-ubuntu-bare-metal-host-with-a-nvidia-gpu

I have tried running multiple GPU's in one machine but it did not work very well in my case (I tried running 4 GPU's) - I think that is because the amount of traffic on the PCIe bus is high with multiple GPUs and the PCIe bus is very slow compared to VRAM.

You can use some sort of GPU monitoring tool to see if the model is loaded in the the VRAM.
I use nvtop on Ubuntu.

Can you build an Ubuntu host? It will be much easier for you and I can share my yaml's with you. Its late here in the USA so can do that tomorrow :-)

Happy 2024!

**Comment by ianpurton** [comment]
@EmmaWebGH 

> Did the ymls above, install what I needed, or it just runs Bionic expecting to see a prior installation of TGI running, that I had installed earlier? Because I didn't. The instructions didn't say I needed that.

Yes the 2nd yml `docker-compose-gpu.yml` overrides some of the config in the first and sets you up with a model running on GPU.

There are no changes required in the GUI (However we need to update the docs to say this)

> Anyway, it seems to work with CPU? By which I mean, it's answering me with the default 7b it comes with (not zephyr?).

It sounds like you have the GPU zephyr model running.

So from our side it's clear we need to make the instructions clearer and perhaps provide a sanity check so people can see the TGI model is running.

**Comment by ianpurton** [comment]
I'll close this out. We've updated the docs to make it clearer (hopefully)

**Comment by EmmaWebGH** [comment]
Thanks for that! Wow that was speedy. :)

Sorry to be dense, but, since it is working, we then add models/change models by changing the yml and relaunching, and not in the GUI? 
What does the "add model" in the "model setup" section do? Only for URL/API based models?

I assume I have to specifically point to the model in the yml, because adding the model to the models folder didn't do it. Changing models during operation would be a great feature.

Can you point me to something that helps me understand how this yaml points to the file on disk? I have a range of models already here I can use. There doesn't seem to be a line that corresponds to the folder name or model file, and the folder for zephyr is also a very different structure to the other models I already have.

Many thanks!

**Comment by ianpurton** [comment]
In the GUI you can add models, for example you can add Open AI (if you have a key). No yml config needed.

If you want to use the TGI inference engine to run models locally, then yes you need to change the yml.

Then in the GUI you can edit the existing model and change the model name and set things like parameters etc.

**Comment by EmmaWebGH** [comment]
Got it
Was confused because I don't consider adding an OpenAI api key to be "adding a model", I thought this was a GUI by which we could load a model. Inability to swap model without closing/opening is a big downside!
But thanks anyway, I will continue to test this out, but I think it's going to get messy with a lot of ymls for a lot of models, very quickly.
Thank you!

**Comment by ianpurton** [comment]
@EmmaWebGH We didn't design it with swapping models in mind. It's more a tool that gets deployed in an enterprise. In which case the models would be setup and change maybe only once a year.

I think there are other tools that let you swap models easily.

**Comment by EmmaWebGH** [comment]
OK, I see. Thanks for explaining!
It's hard to guess sometimes what is for enterprise and what can be used for single users or smaller business.

For my own case, I was approaching from the need of a tool that has LLM + RAG functions, AND with RAG having options. EG, more than 1 vector lib, way to change embedding model, etc. Chat with one vector lib now, another vector lib later. Try out various embedding models. Etc.

But I'm a sole user / small business, and for my use case, having to exit, manually edit ymls, then reboot, is a point of great friction in the experience. But I understand I'm not the target market, and that's OK! :)

Just wanted to let you know, in case this is something you may want to consider, to widen from large enterprise to perhaps smaller businesses that wish to integrate LLMs but won't have it running on servers with a permanent model. Because... it's almost there. Just those friction points, and this could be really really useful to a much wider segment.

There are other tools, as you say - but most lack configurable RAG, if not lacking RAG altogether. Still more lack GPU support. Bionic is one of the very small number that can do LLMs on GPU with RAG (and options for it).

Anyway thanks for all the fast responses, and great work with this app!

**Comment by tbendien** [comment]
HI @EmmaWebGH , I am working on uploading yaml files and docker-exec scripts to my Git using Ollama inference engine that is actually very convenient and pretty easy to us. 

The idea is that you can develop a library of yaml and docker exec files for different models and save them in your Bionic host.

I am also working in next 24 hours to upload my run book so it's easy to change models using Bionic's Ollama integration.

Things to note w/ Ollama integration on Bionic: the GPU VRAM will only be used for the amount needed for the model. I believe that this means that the rest of the avialable VRAM can be used for prompt/response context. This is a good thing.

Also, it seems that Ollama unloads the model from the GPU if it is not used for a while. So when you prompt the model, it may take a few seconds to load into VRAM before responding.

Keep me posted on your thoughts and feedback!

My Bionic Ollama repo is here: https://github.com/tbendien/bionic-ollama-installs

**Comment by EmmaWebGH** [comment]
Hey @tbendien that's super cool! 
Hopefully many people able to use Ollama on Mac and Linux can make use of this.

I'm on Win11 so I don't think Ollama will work for me without some workarounds like WSL - at least until I can pull the trigger on a new mac! ;)
