### ISSUE TITLE
Dedicated GPU storage is nearly full and does not decrease

### ISSUE THREAD

**Issue by felixepiklah** [bionic-gpt/bionic-gpt#277]
Hi Bionic GPT,

The dedicated GPU storage is nearly full and does not decrease after sending some prompt

**1 - Testing Environment**
+ NVDIA GeForce RTX4060 TI 16GB
+ Windows 11 with Docker 
+ Installation step by following this page:
https://bionic-gpt.com/docs/running-locally/gpu-setup/

**2 - Step to reproduce:**
Step 1 - Start docker - dedicated GPU usage does not not increase.
`docker-compose -f docker-compose.yml -f docker-compose-gpu.yml up`
Step 2 - Send something to prompt - the GPU usage increases and never drops down.
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/0d0f7afb-73b1-4cd8-ba3d-8e8a00d472b7)
Step 3 - Stop docker -  dedicated GPU usage decrease
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/37985b1e-9dde-4521-837e-9e523e5613b0)

**3 - Video and log** 
You can check out the video of this issue here
https://drive.google.com/file/d/1dDsi9FQdWp02UjI6NxabPSO8pOShZJZO/view?usp=drive_link 
This is the docker log file
[logs_01_02_2024.txt](https://github.com/bionic-gpt/bionic-gpt/files/13810434/logs_01_02_2024.txt)

Thanks & Regards,
Felix Nguyen

**Comment by kulbinderdio** [comment]
Felix, the GPU setup uses TGI and if a AWQ model has been specified this is loaded fully into VRAM and it also grabs extra to handle batch inference. That is the expected usage.
Other inference engines such as ollama work differently and have a lower memory footprint.
Are you actually getting any issues from this running?

**Comment by felixepiklah** [comment]
Hi, 

I checked and can understand the root cause now.
The AWQ is to accelerate the speed of LLM so it should init the GPU storage for preparation.

This issue is not critical so we can close this ticket.

Thanks & Regards,
Felix Nguyen
