### ISSUE TITLE
Doesn't generate any output or return "Error occurred while generating"

### ISSUE THREAD

**Issue by felixepiklah** [bionic-gpt/bionic-gpt#278]
Hi BionicGPT, 

**1 - Testing Environment**
+ NVDIA GeForce RTX4060 TI 16GB
+ Windows 11 with Docker
+ Installation step by following this page:
https://bionic-gpt.com/docs/running-locally/gpu-setup/
+ Document test: 
[tesla-q2-2023.pdf](https://github.com/bionic-gpt/bionic-gpt/files/13810461/tesla-q2-2023.pdf)

**2 - Step to reproduce**

Step 1: Create new dataset & upload document.
Step 2:  Create new prompt config & link to specific dataset (Default model llama-2-7b)
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/5ab7c6ba-b259-4f00-ae50-741865a38fd5)
Step 3: In Chat Console, select Prompt config and send some request related to document.
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/a22f360e-ac61-41ec-bc98-40af242818af)

**3 - Log**
[no_return_log-01-02-2023.txt](https://github.com/bionic-gpt/bionic-gpt/files/13810556/no_return_log-01-02-2023.txt)

Thanks & Best Regards,
Felix Nguyen

**Comment by ianpurton** [comment]
> tgi-1             | 2024-01-02T13:55:01.456401Z ERROR generate_stream{parameters=GenerateParameters { best_of: None, temperature: Some(0.7), repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: Some(1024), return_full_text: Some(false), stop: [], truncate: None, watermark: false, details: true, decoder_input_details: false, seed: None, top_n_tokens: None }}:async_stream:generate_stream: text_generation_router::infer: router/src/infer.rs:110: `inputs` tokens + `max_new_tokens` must be <= 2048. Given: 1088 `inputs` tokens and 1024 `max_new_tokens`

Looks like we're overfilling the prompt.

On the advanced section of the prompt screen, can you lower the trim ratio?

**Comment by felixepiklah** [comment]
Hi,

I am still got the issue after trying to use the same configuration from this guide.

1) What is trim ratio range should I use on this case?
2) Do I need to configure anything before upload the document to dataset?
3) I created a new Prompt config, this config cannot set "Alternative to Temperature" to 0.1 like default prompt config.

Could you please help me check on this case?
Thank you
