### ISSUE TITLE
build deploy container issue

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#280]
please help to resolve this issue 
![Capture d’écran 2024-01-03 135811](https://github.com/bionic-gpt/bionic-gpt/assets/2206468/e0f29086-f0ba-403f-afa9-0ce360f787b4)

**Comment by ianpurton** [comment]
Runs in our pipeline https://github.com/bionic-gpt/bionic-gpt/actions/runs/7397388932

**Comment by robertsmaoui** [comment]
i should make : git update-index --chmod=+x patch-turbo.sh

thank you
