### ISSUE TITLE
Download chat session prompts and responses

### ISSUE THREAD

**Issue by dnmorris7** [bionic-gpt/bionic-gpt#286]
### Discussed in https://github.com/bionic-gpt/bionic-gpt/discussions/233

<div type='discussions-op-text'>

<sup>Originally posted by **tbendien** December 13, 2023</sup>
Could you make it possible for an end user and a team admin to download prompt and response history please?

This would be be really helpful for end users so they can download the work they have done vs copy and pasting from each window.

The auditing use case is for when a manager or an auditor want to review the prompts and responses from an individual user or a team. </div>

**Comment by tbendien** [comment]
@dnmorris7 there is a way to obtain chat history by querying the postgres database.

I will post a yaml file and instructions on my Git repo in the next few hours with instructions on how to do this.

@ianpurton let us know if you have a plan to or can just add a "copy text" button to the web chat ui?

**Comment by ianpurton** [comment]
@dnmorris7 So maybe we leave this issue for now and perhaps look at https://github.com/bionic-gpt/bionic-gpt/issues/242 instead?

**Comment by dnmorris7** [comment]
The copy feature could be simpler to implement. I will look further into
it.
