### ISSUE TITLE
Envoy container version 1.5.9 fails to start on mac os 14.2.1

### ISSUE THREAD

**Issue by cortizgomez** [bionic-gpt/bionic-gpt#288]
Test PC:
Mac Studio with M2 Ultra, 128 GB shared memory.
Mac OS 14.2.1
docker 24.0.7

Steps:
In a terminal run:
`curl -O https://raw.githubusercontent.com/purton-tech/bionicgpt/main/docker-compose.yml`

After the file is downloaded,
run `docker-compose -f docker-compose.yml`

the command will fail a couple of times because the health check for the keycloak container  fails. waiting 30 secs for keycloak to become healthy seems to fix that issue.

run `docker-compose -f docker-compose.yml` again

the envoy container will fail to start with the following error:
 
bionic-gpt-envoy-1           | rosetta error: bss_size overflow
bionic-gpt-envoy-1           |  
bionic-gpt-envoy-1 exited with code 133

container logs :
Executing task: docker logs --tail 1000 -f 96cd7b383cbdddbd9ef57f1a2ecacc7a6fe02450a5322c02c7689e11dd6045de 

rosetta error: bss_size overflow
 rosetta error: bss_size overflow
 rosetta error: bss_size overflow
 rosetta error: bss_size overflow
 rosetta error: bss_size overflow
 rosetta error: bss_size overflow
 rosetta error: bss_size overflow
 rosetta error: bss_size overflow

**Comment by tbendien** [comment]
try running these yamls from December, it does not include oauth, so is easier to use. 

Users can just sign up, they don't need to be invited. Fine for testing.
[
](https://github.com/tbendien/bionic)

**Comment by ianpurton** [comment]
@cortizgomez We did upgrade the envoy container to the latest envoy.

Can you let me know if an older version runs for you. Replace the envoy container with.

```
ghcr.io/bionic-gpt/bionicgpt-envoy:1.4.14
```

**Comment by cortizgomez** [comment]
> @cortizgomez We did upgrade the envoy container to the latest envoy.
> 
> Can you let me know if an older version runs for you. Replace the envoy container with.
> 
> ```
> ghcr.io/bionic-gpt/bionicgpt-envoy:1.4.14
> ```

Thank you @ianpurton version 1.4.14 does work for me.

**Comment by ianpurton** [comment]
latest docker-compose.yml removes envoy.
