### ISSUE TITLE
Cannot send email invites

### ISSUE THREAD

**Issue by eyalspier** [bionic-gpt/bionic-gpt#289]
Hi there, 
Am attempting to send email invites, but it isn't working. 

The container logs give me the following message:
`Could not send email: lettre::transport::smtp::Error { kind: Connection, source: Custom { kind: Uncategorized, error: "failed to lookup address information: Name does not resolve" } }`

My email settings are:
```yaml
      environment:
   
        - SMTP_HOST='smtp-relay.brevo.com'
        - SMTP_USERNAME='myaddress@gmail.com'
        - SMTP_PASSWORD='passwordstringhere'
        - SMTP_PORT=587
        - INVITE_DOMAIN='bionicgpt.mydomain.com'
        - INVITE_FROM_EMAIL_ADDRESS='myaddress@gmail.com'
```

Is there anything I'm  doing wrong here?

**Comment by ianpurton** [comment]
It might be having troubke finding `smtp-relay.brevo.com` but it also might do a lookup on `bionicgpt.mydomain.com` at the provider side.

**Comment by ianpurton** [comment]
Add this to your docker-compose.yml

```

  # MailHog is an email testing tool for developers.
  smtp:
    image: mailhog/mailhog
    ports:
      8025:8025
```

The set your config to something like

```

      INVITE_DOMAIN: http://oauth2-proxy-selenium:7711
      INVITE_FROM_EMAIL_ADDRESS: support@application.com
      SMTP_HOST: smtp
      SMTP_PORT: 1025
      SMTP_USERNAME: thisisnotused
      SMTP_PASSWORD: thisisnotused
      SMTP_TLS_OFF: 'true'
```

Email should now work and you can access it from localhost:8025

If that's working then, the issue is with your provider and not bionic.

**Comment by eyalspier** [comment]
Hi Ian, 
It works - I'll find another provider. Thanks again for your help on this!
Eyal

**Comment by ianpurton** [comment]
@eyalspier You're welcome.
