### ISSUE TITLE
Redirection after logout (proposal)

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#292]
Hello,

It is possible to redirect user to login page after logout, because it should manually tap in browser the main url of the app to re use the app ?

**Comment by ianpurton** [comment]
Yes. I tried to get it working keycloak supports it. See here https://keycloak.discourse.group/t/logging-out-with-oidc-post-redirect-uri-and-client-id/19343

You're welcome to have a try

**Comment by robertsmaoui** [comment]
Thank you it works !

**Comment by ianpurton** [comment]
Can you let me know what you did so I can add it too?

Or would you like to do a PR ?

**Comment by robertsmaoui** [comment]
Hello @ianpurton 
Simply change the logout url in docker 
LOGOUT_URL: http://localhost:7810/realms/bionic-gpt/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:7800&client_id=bionic-gpt

**Comment by ianpurton** [comment]
Implemented. Thanks.
