### ISSUE TITLE
Got an error doing cpu only install on a VM

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#296]
I did an install on a Ubuntu 22.04 VM with the production docker-compose.yml and Bionic did not come up. 
It is a CPU only install.

Error message was:

ERROR: for oauth2-proxy  Container "1c33f8c074e7" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by ianpurton** [comment]
Can you try it again

**Comment by tbendien** [comment]
turns out that there was a setting on my hypervisor (Proxmox) for the processor type that needed to be set to "host"mode, vs virtualized. Host mode is when the VM compute is passed directly to the host CPU hardware and that all the instruction sets from the CPU are passed to the VM. That fixed this issue. Something to keep in mind for others that may be running Bionic on hypervisors..
