### ISSUE TITLE
Not able to chat

### ISSUE THREAD

**Issue by himansusb** [bionic-gpt/bionic-gpt#298]
I have just installed as a docker container and opened  the UI at localhost. When I submit a prompt it shows the following error on the console. I created new prompts and tried but no luck. Please help

Here is the console log

oauth2-proxy-1    | 172.18.0.1:37684 - a0036c44-9336-41a3-a41c-9785b4cc54e3 - himansusb@gmail.com [2024/01/06 03:44:27] localhost:7800 GET / "/static/commit-t-6ANMvO.svg" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 200 492 0.042
llm-api-1         | 
llm-api-1         |             LiteLLM Warning: proxy started with `ollama` model
llm-api-1         | `ollama serve` failed with Exception[Errno 2] No such file or directory: 'ollama'. 
llm-api-1         | Ensure you run `ollama serve`
llm-api-1         |         
llm-api-1         | 
llm-api-1         | #------------------------------------------------------------#
llm-api-1         | #                                                            #
llm-api-1         | #       'This feature doesn't meet my needs because...'       #
llm-api-1         | #        https://github.com/BerriAI/litellm/issues/new        #
llm-api-1         | #                                                            #
llm-api-1         | #------------------------------------------------------------#
llm-api-1         | 
llm-api-1         |  Thank you for using LiteLLM! - Krrish & Ishaan
llm-api-1         | 
llm-api-1         | 
llm-api-1         | 
llm-api-1         | Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
llm-api-1         | 
llm-api-1         | 
llm-api-1         | 
llm-api-1         | LiteLLM: Test your local proxy with: "litellm --test" This runs an openai.ChatCompletion request to your proxy [In a new terminal tab]
llm-api-1         | 
llm-api-1         | LiteLLM: Curl Command Test for your local proxy
llm-api-1         |  
llm-api-1         |     curl --location 'http://0.0.0.0:8000/chat/completions' \
llm-api-1         |     --header 'Content-Type: application/json' \
llm-api-1         |     --data ' {
llm-api-1         |     "model": "gpt-3.5-turbo",
llm-api-1         |     "messages": [
llm-api-1         |         {
llm-api-1         |         "role": "user",
llm-api-1         |         "content": "what llm are you"
llm-api-1         |         }
llm-api-1         |     ]
llm-api-1         |     }'
llm-api-1         |     
llm-api-1         | 
llm-api-1         |      
llm-api-1         | 
llm-api-1         | Docs: https://docs.litellm.ai/docs/simple_proxy
llm-api-1         | 
llm-api-1         | INFO:     172.18.0.7:40996 - "POST /v1/chat/completions HTTP/1.1" 200 OK
llm-api-1         | ERROR:    Exception in ASGI application
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
llm-api-1         |     result = await app(  # type: ignore[func-returns-value]
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
llm-api-1         |     return await self.app(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1106, in __call__
llm-api-1         |     await super().__call__(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
llm-api-1         |     await self.middleware_stack(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
llm-api-1         |     await self.app(scope, receive, _send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
llm-api-1         |     await self.app(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
llm-api-1         |     await self.app(scope, receive, sender)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
llm-api-1         |     raise e
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
llm-api-1         |     await self.app(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
llm-api-1         |     await route.handle(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
llm-api-1         |     await self.app(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
llm-api-1         |     await response(scope, receive, send)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 277, in __call__
llm-api-1         |     await wrap(partial(self.listen_for_disconnect, receive))
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
llm-api-1         |     raise exceptions[0]
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 273, in wrap
llm-api-1         |     await func()
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 262, in stream_response
llm-api-1         |     async for chunk in self.body_iterator:
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 707, in async_data_generator
llm-api-1         |     async for chunk in response:
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 204, in _async_streaming
llm-api-1         |     raise exception_type(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4634, in exception_type
llm-api-1         |     raise e
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4501, in exception_type
llm-api-1         |     raise ServiceUnavailableError(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/exceptions.py", line 92, in __init__
llm-api-1         |     super().__init__(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/openai/_exceptions.py", line 79, in __init__
llm-api-1         |     super().__init__(message, response.request, body=body)
llm-api-1         | AttributeError: 'NoneType' object has no attribute 'request'
oauth2-proxy-1    | 2024/01/06 03:44:28 httputil: ReverseProxy read error during body copy: unexpected EOF
oauth2-proxy-1    | 172.18.0.1:37684 - 3a921feb-ad66-4242-a614-1a37e872c39e - himansusb@gmail.com [2024/01/06 03:44:28] localhost:7800 POST / "/app/team/1/update_response" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 303 0 0.015
oauth2-proxy-1    | 172.18.0.1:37684 - bc0f6386-cba6-48b5-8d5a-13454d3014e1 - himansusb@gmail.com [2024/01/06 03:44:28] localhost:7800 GET / "/app/team/1/console/1" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 200 9146 0.004
app-1             | 2024-01-06T03:44:28.485218Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
app-1             | 2024-01-06T03:44:28.485308Z  INFO axum_server::prompt: Retrieved 0 chunks
app-1             | 2024-01-06T03:44:28.486299Z  INFO axum_server::prompt: Retrieved 0 history items
app-1             | 2024-01-06T03:44:28.486367Z  INFO axum_server::prompt: Using context size of 1024

**Comment by ianpurton** [comment]
Looks like you don't have ollama running

**Comment by himansusb** [comment]
Isn't this run by docker ?

Should I run ollama in my local or as a separate docker container ?

**Comment by ianpurton** [comment]
For the ollama setup you have to run it yourself. This is because on apple silicon ollama will run natively for gpu.

**Comment by himansusb** [comment]
Hi @ianpurton 
Even after installing ollama and running llama2 locally, I get the same errors. Please help

**Comment by squeeze-twong** [comment]
Any updates on this?

**Comment by lucasarnulphy** [comment]
Im getting the exact same issue, any idea what's happening ? The doc is kind of light.

**Comment by squeeze-twong** [comment]
lucasarnulphy I have a working setup and completely forget I asked for an update. What's your docker yml files look like. I might be able to help.

**Comment by lucasarnulphy** [comment]
The current one in the doc, with localhosts replaced by the machine's ip, except for the healthcheck.

**Comment by squeeze-twong** [comment]
Here's my ollama setting to use GPU, below. Ensure you have https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html installed on the host.

I added volumes to persist my llm downloads, and instructions to use all gpu's (NVIDIA Only).
Unsure if you are using another llm but, I've been downloading new llms manually following this command:
`docker -exec -ti bionic-ollama-1 ollama pull mixtral`

```
services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
```
