### ISSUE TITLE
latest docker-compose-ollama file not starting bionic_ollama_1 container..

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#303]
I am using the latest docker-compose-ollama.yml file (I am not sure if anything changed due to the latest release of the main docker-compose.ymlfile) and it does not appear to be starting the bionic_ollama_1 container, so Ollama can't connect to anything when I run:

docker exec -it bionic_ollama_1 ollama run llama2:13b
Error response from daemon: No such container: bionic_ollama_1

My sequence of commands (using the latest version of docker-compose files) are:

docker-compose -f docker-compose.yml -f docker-compose-ollama.yml up

logs are attached below..
[Bionic error logs - Ollama container not starting.pdf](https://github.com/bionic-gpt/bionic-gpt/files/13852296/Bionic.error.logs.-.Ollama.container.not.starting.pdf)

**Comment by tbendien** [comment]
note that with an older version of the main docker-compose-ollama.yml file, the bionic_ollama_1 container does start ok.

**Comment by ianpurton** [comment]
Do you have ollama running on your machine?

The docker file doesn't run ollama for you.

**Comment by tbendien** [comment]
I just ran:

curl https://ollama.ai/install.sh | sh

so Ollama should be installed on the machine.
I fixed this with Dio the other day and I believe he mentioned that I can just use the Bionic yaml to install Ollama.

@ianpurton would be great if you can provide a "Dummies Guide" on how to run models with Ollama and Bionic. I have it running on another machine but can't remember how I installed it....

**Comment by tbendien** [comment]
I'm going to do a clean install from scratch and see how that goes. My understanding from Dio is that using your docker-compose-ollama.yml downloads add installs Ollama automatically?

**Comment by tbendien** [comment]
this is the Ollama yaml that works on one of my machines, I will try that:

gtadmin@gtaiquadgpu:~/bionic$ cat docker-compose-ollama-llama2-13b.yml 
services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [gpu]

  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    command: ["/bin/sh", "-c", "pip install async_generator && litellm --model ollama/llama2:13b --api_base http://ollama:11434 --host 0.0.0.0 --port 3000"]
    entrypoint: []
    platform: linux/amd64
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
