### ISSUE TITLE
Empty text & embeddings  in DB

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#307]
I uploaded an epub document and saw no errors in the logs
Checked the database and saw empty records

![image](https://github.com/bionic-gpt/bionic-gpt/assets/4700433/6b75047f-bce5-4727-8873-9b799486f143)

Can't attached epub documents to this issue

**Comment by ianpurton** [comment]
Try to find a document you can attach that reproduces this?

Then use the unstructured docker container to reproduce.

```sh
docker run -it -p 8000:8000 downloads.unstructured.io/unstructured-io/unstructured-api:4ffd8bc
```

You can also try the latest version of unstructured to see if it fixes it.

```
curl -X 'POST' \
'http://localhost:8000/general/v0/general' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'files=@PG-test-data.csv' \
-F 'combine_under_n_chars=500' \
-F 'new_after_n_chars=1000' \
-F 'multipage_sections=true' \
-F 'chunking_strategy=by_title' \
| jq -C .
```

If the latest unstructured does it as well, raise an issue and ink to here.

**Comment by 9876691** [comment]
Closing. User didn't provide feedback.
