### ISSUE TITLE
Rag feature works only using ghcr.io/bionic-gpt/llama-2-7b-chat

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#310]
### Describe your issue

Rag feature works only using ghcr.io/bionic-gpt/llama-2-7b-chat

### Describe your setup/startup scripts

i tested many ways , it works fine in chat without datasets, but Rag not works (Error occurred while generating)

### Steps to reproduce

if someone have success Rag without using ghcr.io/bionic-gpt/llama-2-7b-chat, 
please share this, 

litellm not works

**Comment by kulbinderdio** [comment]
@robertsmaoui  How did you change the model?
were you trying with ollama or TGI (2 different config files, docker-compose-ollama.yml & docker-compose-gpu.yml)

what was the error msg shown?
Are you able to share the config files you used? 
On what hardware were you trying?

**Comment by robertsmaoui** [comment]
@kulbinderdio thank you,
i resolved now , it works , i use litellm and ollama for cpu server,
