### ISSUE TITLE
"Error occurred while generating" occurs randomly

### ISSUE THREAD

**Issue by robertsmaoui** [bionic-gpt/bionic-gpt#318]
### Describe your issue

I used openai model gpt3.5 https://api.openai.com/v1/
in chat console , sometimes "Error occurred while generating" occurs especially for the second or third message.

sometimes the response starts to occur then suddenly the response disappears and the error is displayed,

I wanted to test with openai to eliminate the problems of slowness and quality of the server used

### Describe your setup/startup scripts

i tested with jupyter :8888/lab , response with succes (many times tested) :

### Steps to reproduce

url https://api.openai.com/v1/chat/completions   -H "Content-Type: application/json"   -H "Authorization: Bearer sk-VBQuvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvARjPSfi8VE"   -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
                "role": "user",
                "content": "Who won the world series in 2020?"
        },
        {
                "role": "assistant",
                "content": "The Los Angeles Dodgers won the World Series in 2020."
        },
        {
                "role": "user",
                "content": "thank you very much"
        }
]
  }'
{
  "id": "chatcmpl-8fT5YhGFwvy47qpqhEwgpznjn9Jb3",
  "object": "chat.completion",
  "created": 1704893956,
  "model": "gpt-3.5-turbo-0613",
  "choices": [
    {
      "index": 0,
      "message": {
        "role": "assistant",
        "content": "You're welcome! If you have any more questions, feel free to ask."
      },
      "logprobs": null,
      "finish_reason": "stop"
    }
  ],
  "usage": {
    "prompt_tokens": 42,
    "completion_tokens": 16,
    "total_tokens": 58
  },
  "system_fingerprint": null
}

**Comment by robertsmaoui** [comment]
demo
https://github.com/bionic-gpt/bionic-gpt/assets/2206468/2cde07c9-0fea-4d61-8986-76ad2e1a6f95

https://github.com/bionic-gpt/bionic-gpt/assets/2206468/312997af-1df3-4ff0-bab4-d8f6a6109391

**Comment by ianpurton** [comment]
@robertsmaoui Thanks for this. We'll take a look.

**Comment by robertsmaoui** [comment]
@ianpurton thank you ,

the error is more frequent for the French language and less frequent in English

maybe it's due to characters like apostrophes in the response received

**Comment by robertsmaoui** [comment]
I think the error depends on the message received by the model which is changing.
and when the error comes, I can't see the response that caused it.
to cause the error, you can test with messages in French

**Comment by robertsmaoui** [comment]
Hello @ianpurton , 
Here is the log generated by the console when the error was displayed 
[1705146750720.log](https://github.com/bionic-gpt/bionic-gpt/files/13927935/1705146750720.log)
You notice in line 432 the json response is not complete !

Thank you
