### ISSUE TITLE
TGI failed to start after routine apt update

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#320]
### Describe your issue

I shut down Bionic and did a regular Ubuntu apt update and apt upgrade.
There were no hardware changes.
After that, TGI failed to start.
I updated NVIDIA and Ubuntu drivers.
Rebooted.
So the host is now not usable.
My next step would be to reinstall Ubuntu and try a fresh install..

### Describe your setup/startup scripts

gtadmin@gtaiws2:~/bionic$ docker-compose -f bionic-docker-compose-dec2023.yml -f bionic-docker-compose-gpu-dec2023.yml -f docker-compose-pgadmin.yml up

### Steps to reproduce

run the yamls below.

### What was the expected result?

I expected to be able to do a routine Ubuntu update, start Bionic and have it work normally.
FYI I am using Yamls and containers from December so there the problem may not happen with newer containers?

### Any additional information

Yamls:

gtadmin@gtaiws2:~/bionic$ cat bionic-docker-compose-dec2023.yml 
services:

  llm-api:
    image: ghcr.io/bionic-gpt/llama-2-7b-chat:1.0.4
    platform: linux/amd64

  embeddings-api:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.2.2
    platform: linux/amd64
    command: --model-id BAAI/bge-small-en-v1.5

  # Handles parsing of multiple documents types.
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8
    platform: linux/amd64
    ports:
      - "8000:8000"

  # Handles routing between the application, barricade and the LLM API
  envoy:
    image: ghcr.io/bionic-gpt/bionicgpt-envoy:1.4.14
    platform: linux/amd64
    ports:
      - "7800:7700"

  # Postgres pre-loaded with pgVector
  # To connect outside docker `docker compose exec db psql -U postgres`
  db:
    image: ankane/pgvector
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: finetuna
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sets up our database tables
  migrations:
    image: ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.4.14
    platform: linux/amd64
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy

  # Barricade handles all /auth routes for user sign up and sign in.
  barricade:
    image: purtontech/barricade
    platform: linux/amd64
    environment:
        # This secret key is used to encrypt cookies.
        SECRET_KEY: 190a5bf4b3cbb6c0991967ab1c48ab30790af876720f1835cbbf3820f4f5d949
        DATABASE_URL: postgresql://ft_authentication:testpassword@db:5432/postgres?sslmode=disable
        FORWARD_URL: app
        FORWARD_PORT: 7703
        REDIRECT_URL: /app/post_registration
        RUST_LOG: warn
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  pipeline-job:
    image: ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.4.14
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  app:
    image: ghcr.io/bionic-gpt/bionicgpt:1.4.14
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://ft_application:testpassword@db:5432/postgres?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

gtadmin@gtaiws2:~/bionic$ cat bionic-docker-compose-gpu-dec2023.yml
services:

  tgi:
    image: ghcr.io/huggingface/text-generation-inference:1.2
    command: --model-id TheBloke/zephyr-7B-beta-AWQ --max-batch-prefill-tokens 2048 --quantize awq
    volumes:
      - ./models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  llm-api:
    image: ghcr.io/berriai/litellm:main-v1.10.3
    
    command:
      - /bin/sh
      - -c
      - |
        pip install async_generator
        litellm --model huggingface/TheBloke/zephyr-7B-beta-AWQ --api_base http://tgi/generate_stream --host 0.0.0.0 --port 3000
    entrypoint: []
    
    platform: linux/amd64
    gtadmin@gtaiws2:~/bionic$ 

Logs:

gtadmin@gtaiws2:~/bionic$ docker-compose -f bionic-docker-compose-dec2023.yml -f bionic-docker-compose-gpu-dec2023.yml -f docker-compose-pgadmin.yml up
Creating network "bionic_default" with the default driver
Creating volume "bionic_pgadmin-data" with default driver
Pulling pgadmin (dpage/pgadmin4:)...
latest: Pulling from dpage/pgadmin4
661ff4d9561e: Pull complete
5afa59b8f408: Pull complete
2d4a6138fafc: Pull complete
8fb424a8a983: Pull complete
0011ff13e560: Pull complete
13f0840603e2: Pull complete
42a4ae4e73a6: Pull complete
91c1c38904e7: Pull complete
fb06a9fc0ca4: Pull complete
779b87a8a026: Pull complete
dc7968d095ac: Pull complete
2716e11486a8: Pull complete
54175cb5dd12: Pull complete
d5ccf38e9033: Pull complete
7008c2bb0275: Pull complete
618162bf675e: Pull complete
Digest: sha256:3b480788bfd84c9c46f09ce4984867f36fa8b8d8736b2044b376506cb0702ae2
Status: Downloaded newer image for dpage/pgadmin4:latest
Pulling db (ankane/pgvector:)...
latest: Pulling from ankane/pgvector
a803e7c4b030: Pull complete
12dd3b657e91: Pull complete
147adba297eb: Pull complete
56ee7c0dd616: Pull complete
f9aacf30f429: Pull complete
7ad57b8030eb: Pull complete
786562b3be85: Pull complete
04efcdd3a2a4: Pull complete
2c35234636c9: Pull complete
6e662fa63f18: Pull complete
f1a157d7d7b0: Pull complete
bb153abf3802: Pull complete
7077e54346e0: Pull complete
2e3723549f11: Pull complete
c5f09b500022: Pull complete
Digest: sha256:956744bd14e9cbdf639c61c2a2a7c7c2c48a9c8cdd42f7de4ac034f4e96b90f8
Status: Downloaded newer image for ankane/pgvector:latest
Pulling unstructured (downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8)...
c30a2b8: Pulling from unstructured-io/unstructured-api
1a5eb4db1701: Pull complete
a329b64b28e3: Pull complete
429426f26f83: Pull complete
af6382569d4a: Pull complete
524b424c1957: Pull complete
0f0569ebeaaf: Pull complete
4f4fb700ef54: Pull complete
914be7d9a0f4: Pull complete
ed4a7f1888f2: Pull complete
089433c98414: Pull complete
a7df413234bf: Pull complete
95aca52b713e: Pull complete
83aca0ff3f05: Pull complete
e497798f3839: Pull complete
dfcbeaf1eff0: Pull complete
Digest: sha256:008dd6e563b43e680d3e737b45089ed7a49bb95ebac0104b1bfd449ec5d143a5
Status: Downloaded newer image for downloads.unstructured.io/unstructured-io/unstructured-api:c30a2b8
Pulling tgi (ghcr.io/huggingface/text-generation-inference:1.2)...
1.2: Pulling from huggingface/text-generation-inference
96d54c3075c9: Pulling fs layer
755e535b54a3: Pulling fs layer
24ff69e0a1e4: Pulling fs layer
76a627ca5e65: Pull complete
35817692a87e: Pull complete
4f4fb700ef54: Pull complete
99b06da897e0: Pull complete
b7035be95811: Pull complete
71e1c0718878: Pull complete
3fc984233712: Pull complete
19ece81b6895: Pull complete
3b636714e3d8: Pull complete
6c121b71bfd2: Pull complete
e3cae23e7c11: Pull complete
f516f0e01126: Pull complete
f4280016cece: Pull complete
f6edb07bbc73: Pull complete
71fe9c30ca4b: Pull complete
36608ad885b7: Pull complete
f7cd4f82fa50: Pull complete
ab8d20e07ec6: Pull complete
e7ff605488ed: Pull complete
96f2bb47e73f: Pull complete
04156ab1eea9: Pull complete
22ae5bfc3111: Pull complete
9029139fe35d: Pull complete
Digest: sha256:21cbf670fd9dd4bc6ec927b91c421043464ce57bf09df7cb4f2669d3aefd0815
Status: Downloaded newer image for ghcr.io/huggingface/text-generation-inference:1.2
Pulling envoy (ghcr.io/bionic-gpt/bionicgpt-envoy:1.4.14)...
1.4.14: Pulling from bionic-gpt/bionicgpt-envoy
feac53061382: Pull complete
705288059392: Pull complete
dc16693720e7: Pull complete
8865e823f087: Pull complete
e9cd5d0f2387: Pull complete
aa372b911748: Pull complete
70e3802cf6d3: Pull complete
f7711b743959: Pull complete
6704e1e593f2: Pull complete
16e26ed7429b: Pull complete
Digest: sha256:cb36c73acd36ae155fad7997499d381bb8c55c845eda31becf49b166a2f183e8
Status: Downloaded newer image for ghcr.io/bionic-gpt/bionicgpt-envoy:1.4.14
Pulling migrations (ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.4.14)...
1.4.14: Pulling from bionic-gpt/bionicgpt-db-migrations
661ff4d9561e: Already exists
8e69add9ab25: Pull complete
446bd28e6bad: Pull complete
f810b1e5871a: Pull complete
Digest: sha256:f544240b163b1165c92287291af983b345e24fe6644f6cbc4f5e94ef3a1a7caf
Status: Downloaded newer image for ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.4.14
Pulling barricade (purtontech/barricade:)...
latest: Pulling from purtontech/barricade
dd5f8dd6668e: Pull complete
Digest: sha256:0bcf4998ba71be79f308dddce08cb0a1c4ae9a7eb73080e2cd2396c1ef67dc63
Status: Downloaded newer image for purtontech/barricade:latest
Pulling app (ghcr.io/bionic-gpt/bionicgpt:1.4.14)...
1.4.14: Pulling from bionic-gpt/bionicgpt
07fd26bc9e7f: Pull complete
535758fade77: Pull complete
d59065af3c29: Pull complete
Digest: sha256:08f1f5ba1cebd7884c7e938c0dc9b1a056ba536857edd1f6a88bc1aa04cb7ce1
Status: Downloaded newer image for ghcr.io/bionic-gpt/bionicgpt:1.4.14
Pulling llm-api (ghcr.io/berriai/litellm:main-v1.10.3)...
main-v1.10.3: Pulling from berriai/litellm
1f7ce2fa46ab: Pull complete
442c5d63eafd: Pull complete
342f11d60b1e: Pull complete
57b3e82cff54: Pull complete
ec926eb426a4: Pull complete
218e90632a46: Pull complete
d91d815d062a: Pull complete
ae9e13b38ae6: Pull complete
345f6afe7e57: Pull complete
f3aaaed157a5: Pull complete
Digest: sha256:7858f7d8f0e0955f3bbe8dcbb123be4d15af7b79690f719c3067098cab474cb3
Status: Downloaded newer image for ghcr.io/berriai/litellm:main-v1.10.3
Pulling pipeline-job (ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.4.14)...
1.4.14: Pulling from bionic-gpt/bionicgpt-pipeline-job
8d18cf249aef: Pull complete
Digest: sha256:e93d557d769c446712ac2a037a622446bbb03e8e78312e7670aac47b2b63524c
Status: Downloaded newer image for ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.4.14
Pulling embeddings-api (ghcr.io/huggingface/text-embeddings-inference:cpu-0.2.2)...
cpu-0.2.2: Pulling from huggingface/text-embeddings-inference
a378f10b3218: Pull complete
8070ca914b13: Pull complete
5d601df67a5d: Pull complete
Digest: sha256:a3b3e470165eaba1eb89972ca029dc39ad2879cd3ce042e528eb87a3c149be1c
Status: Downloaded newer image for ghcr.io/huggingface/text-embeddings-inference:cpu-0.2.2
Creating bionic_unstructured_1 ... 
Creating bionic_llm-api_1        ... done
Creating bionic_pgadmin_1      ... 
Creating bionic_embeddings-api_1 ... done
Creating bionic_unstructured_1   ... done
Creating bionic_db_1             ... 
Creating bionic_pgadmin_1        ... done

ERROR: for bionic_tgi_1  Cannot start service tgi: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start conCreating bionic_db_1             ... done
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown
Creating bionic_migrations_1     ... done
Creating bionic_barricade_1      ... done
Creating bionic_pipeline-job_1   ... done
Creating bionic_app_1            ... done

ERROR: for tgi  Cannot start service tgi: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown
ERROR: Encountered errors while bringing up the project.
gtadmin@gtaiws2:~/bionic$

**Comment by ianpurton** [comment]
Please before posting look at any errors and try google first.

`nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown`

https://github.com/NVIDIA/nvidia-docker/issues/1393
