### ISSUE TITLE
Support adding models in K8's

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#328]
## We generate models for cpu and gpu

In the same way we pre-load the embeddings model. We can pre-load and inference engine.

- [ ] Get TGI cpu running on K8's
- [ ] Create example docker for customer to build their own models.
- [ ] Remove demo model i.e. pre-load-model: false
- [ ] Show examples of deploying model and service
- [ ] Have our own base model based on TGI.
- [ ] https://github.com/huggingface/text-generation-inference/pull/1427

## Things to Consider

- [ ] Do we get continuous batching on CPU?
- [ ] How will users split between GPU's
- [ ] IN the config switch off the existing model (and service?)

**Comment by tbendien** [comment]
@ianpurton DYK you can bifurcate certain GPU's? https://forums.developer.nvidia.com/t/best-multi-gpu-method-omniverse-farm-vs-pcie-bifurcation/194630
