### ISSUE TITLE
Changes noticed for postgres DB configs

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#329]
### Describe your issue

I loaded my pgadmin yaml file as attached below and which worked on previous builds of Bionic.
Since the new docker-compose.yml file was released I have not been able to setup a connection to the postgres DB.

I can see the GUI for PGadmin but when I try to set up a connection to the database it fails.
I'm using the default credentials that I have used before many times:

Hostname: db
Port: 5432
Maintenance database: postgres
User: postgres
Password: testpassword

### Describe your setup/startup scripts

gtadmin@aitower1:~/bionic$ docker-compose -f docker-compose.yml -f docker-compose-gpu.yml -f docker-compose-embed-gpu.yml -f docker-compose-pgadmin.yml up

### Steps to reproduce

Splashtop into aitower1 to see the issue.

### What was the expected result?

I expected to set up a connection to the postgres DB as normal which works on my hosts with the December yamls.

### Any additional information

![Screenshot 2024-01-14 at 1 44 05 PM](https://github.com/bionic-gpt/bionic-gpt/assets/47579015/5f372c08-3969-44f0-83b6-4d3f68c4e471)

# Do not expose this configuration to the internet. This is an
# example configuration so that you can try out Bionic GPT.
#
# This is NOT a production configuration.
services:

  llm-api:
    image: ghcr.io/bionic-gpt/llama-2-7b-chat:1.0.4
    platform: linux/amd64

  embeddings-api:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-0.2.2
    platform: linux/amd64
    command: --model-id BAAI/bge-small-en-v1.5

  # Document parsing, OCR and chunking.
  # Image tagged with the short commit hash (e.g. fbc7a69) for each pust to main
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:4ffd8bc
    platform: linux/amd64

  # We use Oauth2 Proxy as the interface to our OIDC provider
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    platform: linux/amd64
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:7800
      OAUTH2_PROXY_COOKIE_SECRET: OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w=
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_UPSTREAMS: http://app:7703
      OAUTH2_PROXY_UPSTREAMS_TIMEOUT: 600s
      OAUTH2_PROXY_CLIENT_SECRET: 69b26b08-12fe-48a2-85f0-6ab223f45777
      OAUTH2_PROXY_CLIENT_ID: bionic-gpt
      OAUTH2_PROXY_REDIRECT_URL: http://10.32.1.93:7800/oauth2/callback
      OAUTH2_PROXY_OIDC_ISSUER_URL: http://keycloak:7810/realms/bionic-gpt
      OAUTH2_PROXY_INSECURE_OIDC_SKIP_ISSUER_VERIFICATION: "true"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: Keycloak
      OAUTH2_PROXY_AUTH_LOGGING: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_WHITELIST_DOMAINS: "10.32.1.93:7810"
      OAUTH2_PROXY_SKIP_AUTH_ROUTES:  "^/(v1|static)/.*"
    restart: unless-stopped
    ports:
      - 7800:7800
    depends_on:
      keycloak:
        condition: service_healthy

  # We support Open ID Connect. In this case we're using Keycloak
  # But you can use your own identityt provider.
  keycloak:
    image: ghcr.io/bionic-gpt/bionicgpt-keycloak:1.5.22
    platform: linux/amd64
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: testpassword
      KC_DB_USERNAME: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KC_HEALTH_ENABLED: "true"
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=7810"
      - "--proxy=edge"
      - "--hostname=10.32.1.93:7810"
    ports:
      - 7810:7810
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/7810;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://10.32.1.93\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy

  # Postgres pre-loaded with pgVector
  # To connect outside docker `docker compose exec postgres psql -U postgres`
  postgres:
    image: ankane/pgvector
    platform: linux/amd64
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: keycloak
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Sets up our database tables
  migrations:
    image: ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.5.22
    platform: linux/amd64
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@postgres:5432/bionic-gpt?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
  
  # Parses documents into chunks and creates embeddings.
  pipeline-job:
    image: ghcr.io/bionic-gpt/bionicgpt-pipeline-job:1.5.22
    platform: linux/amd64
    environment:
      APP_DATABASE_URL: postgresql://bionic_application:testpassword@postgres:5432/bionic-gpt?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  
  # Our axum server delivering our user interface
  app:
    image: ghcr.io/bionic-gpt/bionicgpt:1.5.22
    platform: linux/amd64
    environment:
      LOGOUT_URL: http://10.32.1.93:7810/realms/bionic-gpt/protocol/openid-connect/logout?post_logout_redirect_uri=http://10.32.1.93:7800&client_id=bionic-gpt
      APP_DATABASE_URL: postgresql://bionic_application:testpassword@postgres:5432/bionic-gpt?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

**Comment by tbendien** [comment]
ok I  figured out the new settings:

![Screenshot 2024-01-14 at 2 43 51 PM](https://github.com/bionic-gpt/bionic-gpt/assets/47579015/fc0d6a73-eafa-4631-b9bd-50490b8f317f)

**Comment by tbendien** [comment]
Also - there are new db's in the postgres servers on the latest version of Bionic.

The DB that has the chat history is called bionic-gpt

@ianpurton if you change the DB configs, could you publish release notes on that? My SQl still seems to run fine once i selected the bionic-gpt DB. Here is my SQL to show chat history:

SELECT
  TO_CHAR(chats.created_at, 'YYYY-MM-DD') AS created_date,
  TO_CHAR(chats.created_at, 'HH24:MI:SS') AS created_time,
  chats.id,
  status,
  email,
  last_name,
  first_name,
  user_request,
  response
FROM users
JOIN conversations ON users.id = conversations.user_id 
JOIN chats ON chats.conversation_id = conversations.id
ORDER BY chats.created_at DESC;

**Comment by tbendien** [comment]
@ianpurton are there any more DB changes that I should be aware of regarding chat history?

**Comment by ianpurton** [comment]
Hostname is postgres
