### ISSUE TITLE
Community Edition Bionic does not work anymore

### ISSUE THREAD

**Issue by tbendien** [bionic-gpt/bionic-gpt#333]
### Describe your issue

When I run the standard default Community Editon docker-compose files, there is an error message and the environment fails to start. 

This makes the CE unusable "out of the box". IMHO there should always be a basic free version of Bionic of some sort (with a limited set of features is fine) that people can use to test it please. Even a basic version of the K8's deployment single node would be fine. If the legacy CE cannot be supported, suggest that it be removed from the repo. 

I believe that in the spirit of the Open Source Community, that Bionic should at least enable their CE deployment work out of the box without needing to troubleshoot it. If not, it should be removed from the repo. 

### Describe your setup/startup scripts

docker-compose -f docker-compose.yml -f docker-compose-gpu.yml -f docker-compose-embed-gpu.yml -f docker-compose-pgadmin.yml up

### Steps to reproduce

download the current CE yamls and try to start Bionic.

### What was the expected result?

I expected Bionic CE to start and run normally with default configs.

### Any additional information

Here are the errors when I try to start Bionic with the current CE yaml files:
gtadmin@gtaiws1:~/bionic$ docker-compose -f docker-compose.yml -f docker-compose-gpu.yml -f docker-compose-embed-gpu.yml -f docker-compose-pgadmin.yml up
Creating network "bionic_default" with the default driver
Creating volume "bionic_pgadmin-data" with default driver
Creating bionic_llm-api_1        ... done
Creating bionic_tgi_1            ... error
Creating bionic_embeddings-api_1 ... 
Creating bionic_unstructured_1   ... done
Creating bionic_postgres_1       ... done
Creating bionic_pgadmin_1        ... done

ERROR: for bionic_tgi_1  Cannot start service tgi: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error runningCreating bionic_embeddings-api_1 ... error
e as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown

ERROR: for bionic_embeddings-api_1  Cannot start service embeddings-api: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver/library version mismatch: unknown
^CGracefully stopping... (press Ctrl+C again to force)
Stopping bionic_pgadmin_1        ... done
Stopping bionic_unstructured_1   ... done
Stopping bionic_llm-api_1        ... done
Stopping bionic_postgres_1       ... done

**Comment by ianpurton** [comment]
NVIDIA driver issue.
