### ISSUE TITLE
bionic-keycloak reporting fatal error

### ISSUE THREAD

**Issue by squeeze-twong** [bionic-gpt/bionic-gpt#339]
### Describe your issue

bionic-keycloak-1        | #
bionic-keycloak-1        | # A fatal error has been detected by the Java Runtime Environment:
bionic-keycloak-1        | #
bionic-keycloak-1        | #  SIGSEGV (0xb) at pc=0x00007fc5a8f2f840, pid=93, tid=94
bionic-keycloak-1        | #
bionic-keycloak-1        | # JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.9.0.9-1) (17.0.9+9) (build 17.0.9+9-LTS)
bionic-keycloak-1        | # Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.9.0.9-1) (17.0.9+9-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, parallel gc, linux-amd64)
bionic-keycloak-1        | # Problematic frame:
bionic-keycloak-1        | # J 77 c1 java.lang.StringUTF16.compress([CI[BII)I java.base@17.0.9 (50 bytes) @ 0x00007fc5a8f2f840 [0x00007fc5a8f2f840+0x0000000000000000]
bionic-keycloak-1        | #
bionic-keycloak-1        | # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to //core.93)
bionic-keycloak-1        | #
bionic-keycloak-1        | # An error report file with more information is saved as:
bionic-keycloak-1        | # /tmp/hs_err_pid93.log
bionic-keycloak-1        | #
bionic-keycloak-1        | # If you would like to submit a bug report, please visit:
bionic-keycloak-1        | #   https://access.redhat.com/support/cases/
bionic-keycloak-1        | #
bionic-app-1             | 2024-01-17T02:39:02.827964Z  INFO axum_server: listening on 0.0.0.0:7703
bionic-keycloak-1        | /opt/keycloak/bin/kc.sh: line 144:    93 Aborted                 (core dumped) 'java' -Dkc.config.build-and-exit=true '-Xms64m' '-Xmx512m' '-XX:MetaspaceSize=96M' '-XX:MaxMetaspaceSize=256m' '-Dfile.encoding=UTF-8' '-Dsun.stdout.encoding=UTF-8' '-Dsun.err.encoding=UTF-8' '-Dstdout.encoding=UTF-8' '-Dstderr.encoding=UTF-8' '-XX:+ExitOnOutOfMemoryError' '-Djava.security.egd=file:/dev/urandom' '-XX:+UseParallelGC' '-XX:MinHeapFreeRatio=10' '-XX:MaxHeapFreeRatio=20' '-XX:GCTimeRatio=4' '-XX:AdaptiveSizePolicyWeight=90' '-XX:FlightRecorderOptions=stackdepth=512' '--add-opens=java.base/java.util=ALL-UNNAMED' '--add-opens=java.base/java.util.concurrent=ALL-UNNAMED' '--add-opens=java.base/java.security=ALL-UNNAMED' -Dkc.home.dir='/opt/keycloak/bin/..' -Djboss.server.config.dir='/opt/keycloak/bin/../conf' -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Dquarkus-log-max-startup-records=10000 -cp '/opt/keycloak/bin/../lib/quarkus-run.jar' io.quarkus.bootstrap.runner.QuarkusEntryPoint --profile=dev start-dev '--import-realm' '--http-port=7810' '--proxy=edge' '--hostname=localhost:7810'
container for service "keycloak" is unhealthy

### Describe your setup/startup scripts

[root@localhost bionic]# curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose/docker-compose.yml
[root@localhost bionic]# docker-compose up

### Steps to reproduce

[root@localhost bionic]# curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose/docker-compose.yml
[root@localhost bionic]# docker-compose up

### Any additional information

Using UTM Linux Emulation on Mac Book Pro M1
Rocky Linux 9 x86_64
CPU Intel Core i7 9xx (Nehelem Class Core i7) (Nahalem-v1) 
6 vCore
Ram 4GB

**Comment by ianpurton** [comment]
4GB RAM is very low 16GB is probably the minimum.

Do you want to directly try the install for m1 https://bionic-gpt.com/docs/running-locally/apple-silicon/

**Comment by ianpurton** [comment]
> I did try the link you provided for silicon has references to linux/amd64 and fails.

Which part fails?

**Comment by squeeze-twong** [comment]
When the keycloak container comes up. The error is in the first post

**Comment by squeeze-twong** [comment]
FYI, I managed to get up and running. Not on the Chromebook, but on the MacBook Pro M3.
