### ISSUE TITLE
ERROR 422 - Unprocessable Entity

### ISSUE THREAD

**Issue by felixepiklah** [bionic-gpt/bionic-gpt#340]
### Describe your issue

Hi BionicGPT,

I got an issue after log out from the app from Chrome and cannot login.

### Describe your setup/startup scripts

docker-compose -f docker-compose.yml -f docker-compose-gpu.yml up

### Steps to reproduce

1) After login from proxy page, it wil; redirect to this page
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/70bc30f2-78d0-46d3-aed0-a5f2adf09680)
status = 422 Unprocessable Entity, message = db error: ERROR: duplicate key value violates unique constraint "users_email_key"
DETAIL: Key (email)=(<email>) already exists.

2) Press back and saw 403 error returned.
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/c2e8bd05-0497-4464-99b4-3b8e80da43a7)
-----
More Info
Login Failed: Unable to find a valid CSRF token. Please try again.
Request ID: 0f8291af-aa22-4a3c-9e8d-dde64dc53189
-----

3) Accesss to page
http://localhost:7810/realms/bionic-gpt/login-actions/authenticate?execution=0f8291af-aa22-4a3c-9e8d-dde64dc53189
it said: You are already login.
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/50c8e0d1-5842-416d-bce8-e8c97e4383c6)

### Any additional information

It seems that there are an cookie issue. Could you please help check on this?

Workaround:
I need to create new account and login, then I cannot access to old account anymore.
Please help give an advice on this case

Thanks & Regards
Felix Nguyen

**Comment by ianpurton** [comment]
Thanks @robertsmaoui
