### ISSUE TITLE
Uploading document doesn't work in k8's

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#343]
This document won't upload. https://project64.c64.org/Software/mlcom.pdf

**Comment by marcelhintermann** [comment]
see similar problems when indexing PDF files.

in pipeline-job:

```
Error: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E22021), message: "invalid byte sequence for encoding \"UTF8\": 0x00", detail: None, hint: None, position: None, where_: Some("unnamed portal parameter $3"), schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("mbutils.c"), line: Some(1665), routine: Some("report_invalid_encoding") }) }
```

in postgres
```
2024-01-24 14:35:03.472 UTC [126] ERROR:  relation "public.databasechangelog" does not exist at character 22
2024-01-24 14:35:03.472 UTC [126] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
2024-01-24 14:35:59.902 UTC [83] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2024-01-24 14:35:59.902 UTC [83] CONTEXT:  unnamed portal parameter $3
2024-01-24 14:35:59.902 UTC [83] STATEMENT:  
	                                INSERT INTO chunks (
	                                    document_id,
	                                    page_number,
	                                    text
	                                ) 
	                                VALUES 
	                                    ($1, $2, $3)
```

ingesting for other files (pptx, xlsx, docx) works fine.

**Comment by 9876691** [comment]
Maybe an issue with upload size in the nginx ingress controller.

See https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

**Comment by 9876691** [comment]
Need to add this to the ingress

```
    # We need toi set this as the max size for document upload
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
```

See https://bionic-gpt.com/docs/enterprise-edition/installing-bionic/

**Comment by mohamedkassem23** [comment]
Hi, i have the same issue. but I'm using the docker-compose setup 

`2024-03-05T11:15:01.737808Z ERROR pipeline_job: error="Not able to parse document {\"detail\":\"list index out of range\"}"
2024-03-05T11:18:21.060427Z ERROR pipeline_job: error="Not able to parse document {\"detail\":\"Can't find workbook in OLE2 compound document\"}"
Error: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E22021), message: "invalid byte sequence for encoding \"UTF8\": 0x00", detail: None, hint: None, position: None, where_: Some("unnamed portal parameter $3"), schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("mbutils.c"), line: Some(1665), routine: Some("report_invalid_encoding") }) }
Error: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E22021), message: "invalid byte sequence for encoding \"UTF8\": 0x00", detail: None, hint: None, position: None, where_: Some("unnamed portal parameter $3"), schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("mbutils.c"), line: Some(1665), routine: Some("report_invalid_encoding") }) }
^C`
