### ISSUE TITLE
Link in instructions on website is wrong.

### ISSUE THREAD

**Issue by powellgithub** [bionic-gpt/bionic-gpt#344]
### Describe your issue

On the webpage:  [https://bionic-gpt.com/docs/enterprise-edition/install-operator/](url)

The last set of instructions are:
`kubectl apply -n bionic-gpt -f https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/crates/config/k8s-operator/bionic-operator.yaml`
That url is incorrect

The correct URL is: 
[https://github.com/bionic-gpt/bionic-gpt/blob/main/crates/k8s-operator/config/bionic-operator.yaml](url)

### Describe your setup/startup scripts

N/A

### Steps to reproduce

Attempt to use the listed instructions.

### What was the expected result?

No error

**Comment by ianpurton** [comment]
@powellgithub Good spot. Thanks for this.
