### ISSUE TITLE
Error occurred while generating in chat console ERROR axum_server

### ISSUE THREAD

**Issue by andresdegante** [bionic-gpt/bionic-gpt#353]
### Describe your issue

When trying to generate text I get an error "An error occurred while generating"
Terminal: ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = query returned an unexpected number of rows"

### Describe your setup/startup scripts

Followed the steps published at https://bionic-gpt.com/docs/running-locally/gpu-setup-ollama/
MacBook Pro
Apple M2 Pro
Sonoma 14.0 (23A344)
16 GB

### Steps to reproduce

Click in chat console
Write text
Click in send message

### What was the expected result?

Text generation

### Any additional information
ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = query returned an unexpected number of rows"

![Captura de pantalla 2024-01-31 a la(s) 5 01 42 p m](https://github.com/bionic-gpt/bionic-gpt/assets/24718767/526b24bf-dae5-48dd-bcad-56a10f40fe4e)
![Captura de pantalla 2024-01-31 a la(s) 5 01 14 p m](https://github.com/bionic-gpt/bionic-gpt/assets/24718767/0fa56ba5-ef46-4439-aefd-1cd44205cae0)

**Comment by uh2023** [comment]
Has this issue been resolved? I am facing the same error.

**Comment by 9876691** [comment]
A fix was added to version 1.5.27, what version are you on?

**Comment by uh2023** [comment]
Yes I'm on the same version. This is the error I get:
ERROR:    Exception in ASGI application
AttributeError: 'NoneType' object has no attribute 'request'

I am pointing at http://llm-api:3000/v1 in the model setup page of the UI.

**Comment by 9876691** [comment]
@uh2023 Needs to be http://llm-api:11434/v1

Re-open if it still doesn't work.

**Comment by mohamedkassem23** [comment]
I am facing the same error. i'm using latest version 1.6.10
