### ISSUE TITLE
entreprise edition loose all data when docker is restarted

### ISSUE THREAD

**Issue by nsunder72** [bionic-gpt/bionic-gpt#355]
### Describe your issue

Please help, i manage to install and run the Kubernetes version but data are not stored properly i am loosing everything except the administrator account

### Describe your setup/startup scripts

i followed every steps in the documentation except it's installed on windows docker desktop and run perfectly well.
the problem doesn't occur when i install the demo version.

### Steps to reproduce

install as shown here: https://bionic-gpt.com/docs/enterprise-edition/installing-bionic/

**Comment by ianpurton** [comment]
@nsunder72 We're still completing the documenation for the enterprise version.

You should create your own Postgres database and use a production version of Kubernetes. Is that what you are doing?

**Comment by ianpurton** [comment]
@nsunder72 It's great you got this all running. I need a couple of days to finalize the docs and some code changes.

**Comment by 9876691** [comment]
Closing. Documentation for running with Postgres has been provided.
