### ISSUE TITLE
Cannot set Alternative to Temperature to 0.x on Custom Prompt profile

### ISSUE THREAD

**Issue by felixepiklah** [bionic-gpt/bionic-gpt#356]
### Describe your issue

To create another custom prompt, I cannot set Alternative to Temperature to 0.1 like Default prompt profile. Could you please give me some advice on this?

### Describe your setup/startup scripts

cker-compose -f docker-compose.yml -f docker-compose-gpu.yml up

### Steps to reproduce

1. Access to the UI
2. Create new prompt
3. In Advanced settings, adjust the "Alternative to Temperature *" to 0.1-0.9 -> Failed
![image](https://github.com/bionic-gpt/bionic-gpt/assets/114893777/615b8edf-fc80-4250-9b63-d98092f613aa)

### What was the expected result?

I can adjust the "Alternative to Temperature *" in the range of 0.1-0.9

**Comment by 9876691** [comment]
@felixepiklah It's fixed, be we currently don't send that value. We will probably remove it.

**Comment by felixepiklah** [comment]
@9876691 thank you.
