### ISSUE TITLE
422 when using a prompt with embeddings

### ISSUE THREAD

**Issue by whalygood** [bionic-gpt/bionic-gpt#360]
### Describe your issue

 Using the default LLM (**llama-2-7b**) and embeddings model (**bge-small-en-v1.5**), I encounter a **422 Unprocessable Entity** error whenever I use a Prompt with a selected dataset. The error shown in the UI is "Error occurred while generating" and an error similar to the below appears in the browser console:

![image](https://github.com/bionic-gpt/bionic-gpt/assets/31971061/30df50c6-7345-4cc4-b4a1-1cc89d2b2f39)

```
status = 422 Unprocessable Entity, message = error decoding response body: EOF while parsing a value at line 1 column 0 streaming-chat.ts:57:28
Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    streamResult streaming-chat.ts:72
    streamResult streaming-chat.ts:56
streaming-chat.ts:93:24
    streamResult streaming-chat.ts:93
```

However, using a prompt with no dataset proceeds normally (text is generated).

The Dataset is a PDF file embedded into a dataset created in the "Team Datasets" area of the UI.

### Describe your setup/startup scripts

I followed the "Practice Installation using Kind" through the "Installing Bionic" steps under "Bionic-GPT - Enterprise Edition" in the docs.

![Screenshot from 2024-02-08 00-43-21](https://github.com/bionic-gpt/bionic-gpt/assets/31971061/4fc50574-113d-4a3c-aba8-0002ce10e1e0)

### Steps to reproduce

1. Create a new Dataset from Team Datasets by clicking "Add Dataset."
2. Then, click "Add Document" and upload the PDF file.
3. Shortly after, refreshing the page will show that the PDF has been "processed" with 30 chunks.
4. Create a new Prompt using the default model, and from the drop-down choose "Selected" for datasets, and select the newly created Dataset from the pick list.
5. Go to the Chat Console, and from the drop down, pick the Prompt that uses the Dataset.
6. The above error will occur.

### What was the expected result?

Text should be generated even when using a prompt with an embedding.

**Comment by 9876691** [comment]
Fixed in latest release.

**Comment by whalygood** [comment]
Wow thanks for the quick work on this! 
Just tried to retest by changing the version numbers in the deployments for the following containers, but still running into the same issue. Is there anything else I should do to test the fix? 

```
ghcr.io/bionic-gpt/bionicgpt:1.5.27
ghcr.io/bionic-gpt/bionicgpt-db-migrations:1.5.27
ghcr.io/bionic-gpt/bionicgpt-k8s-operator:1.5.27
```

**Comment by whalygood** [comment]
Just saw that you pushed 1.5.29 this afternoon. 
Updated the above 3 containers to the 1.5.29 tag in the k8s deployments, and restarted the entire machine for good measure, but still seeing the issue. @9876691 

![image](https://github.com/bionic-gpt/bionic-gpt/assets/31971061/e626e728-a81e-4fff-ad85-9a570b1e95bd)

**Comment by 9876691** [comment]
@whalygood Is it possible to share the document you are using so I can reproduce the issue?

**Comment by whalygood** [comment]
Sure thing @9876691 , here is the document. I suspect it isn't an issue with the specific document, but anything I can do help, please let me know! https://www.commonwealth.virginia.gov/media/governorvirginiagov/secretary-of-the-commonwealth/pdf/2021-Legislation-Revised-Notary-Handbook-2020.pdf

**Comment by 9876691** [comment]
Thanks, just tried it and I get the same issue. Will work on a fix.

**Comment by 9876691** [comment]
Fixed in latest release

**Comment by whalygood** [comment]
Can confirm that the fix allows doing RAG from a PDF embedding using the default model.
