### ISSUE TITLE
I have some dns error even when I removing EMBEDDINGS_API_ENDPOINT 

### ISSUE THREAD

**Issue by brunoAmado** [bionic-gpt/bionic-gpt#367]
I have some dns error even when I removing EMBEDDINGS_API_ENDPOINT (it seams that it use a "default" embedding endpoint but it is not the one I configure for the RAG. see error bellow:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/5504321/17bc369c-86f4-474b-9374-e534d67b1ccf)
removing the need for a DNS when putting a ip another error appear:
![image](https://github.com/bionic-gpt/bionic-gpt/assets/5504321/d25a730f-f222-4330-8ee6-a9691fdc97ed)

_Originally posted by @brunoAmado in https://github.com/bionic-gpt/bionic-gpt/issues/351#issuecomment-1937065841_

**Comment by 9876691** [comment]
Can you update to the latest version as I made a fix yesterday for this.

**Comment by brunoAmado** [comment]
I'm using the version 1.5.32

**Comment by 9876691** [comment]
Currently the embeddings engine configured against a dataset has no bearing on the one selected for the embeddings.

So the following needs to happen.

- [ ] Update crates/embeddings-api/src/lib.rs and pass in api_url and model
- [ ] When getting chunks use the correct model for each dataset

**Comment by 9876691** [comment]
Fixed
