### ISSUE TITLE
Error on the ll-api port on the entreprise edition

### ISSUE THREAD

**Issue by nsunder72** [bionic-gpt/bionic-gpt#374]
### Describe your issue

i get a **undefined** response
<img width="237" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/159088454/60d369e3-8a2a-47bb-a197-6bee37ba0a6d">

### Describe your setup/startup scripts

i use the Kubernetes installation entreprise edition but on port 8843 instead of 443
except that i respected the install in the doc.
<img width="647" alt="image" src="https://github.com/bionic-gpt/bionic-gpt/assets/159088454/8b52d99e-0eeb-4439-a474-2337e64fb982">

### Steps to reproduce

at this stage i found out that the llm-api was listening port 11434 but the endpoint was on 3000

kubectl get endpoints llm-api -n bionic-gpt
NAME      ENDPOINTS          AGE
llm-api   10.244.0.17:3000   5h3m

kubectl get endpoints llm-api -n bionic-gpt
NAME      ENDPOINTS          AGE
llm-api   10.244.0.17:3000   5h3m
(base) PS C:\Users\Administrator> kubectl logs llm-api-58996fc4d5-ns7t5 -n bionic-gpt
time=2024-02-17T16:59:59.491Z level=INFO source=images.go:863 msg="total blobs: 6"
time=2024-02-17T16:59:59.492Z level=INFO source=images.go:870 msg="total unused blobs removed: 0"
time=2024-02-17T16:59:59.492Z level=INFO source=routes.go:999 msg="Listening on [::]:11434 (version 0.1.24)"
time=2024-02-17T16:59:59.492Z level=INFO source=payload_common.go:106 msg="Extracting dynamic libraries..."
time=2024-02-17T17:00:02.149Z level=INFO source=payload_common.go:145 msg="Dynamic LLM libraries [rocm_v5 cpu_avx2 cuda_v11 cpu_avx rocm_v6 cpu]"
time=2024-02-17T17:00:02.149Z level=INFO source=gpu.go:94 msg="Detecting GPU type"
time=2024-02-17T17:00:02.149Z level=INFO source=gpu.go:242 msg="Searching for GPU management library libnvidia-ml.so"
time=2024-02-17T17:00:02.149Z level=INFO source=gpu.go:288 msg="Discovered GPU libraries: []"
time=2024-02-17T17:00:02.149Z level=INFO source=gpu.go:242 msg="Searching for GPU management library librocm_smi64.so"
time=2024-02-17T17:00:02.150Z level=INFO source=gpu.go:288 msg="Discovered GPU libraries: []"
time=2024-02-17T17:00:02.150Z level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-02-17T17:00:02.150Z level=INFO source=routes.go:1022 msg="no GPU detected"

so i applied 

apiVersion: v1
kind: Service
metadata:
  name: llm-api
  namespace: bionic-gpt
spec:
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 11434 # Change this to match the application's listening port
  selector:
    app: llm-api
  type: ClusterIP
  
  and it did look like working in the logs

  kubectl logs llm-api-58996fc4d5-ns7t5 -n bionic-gpt
time=2024-02-17T22:16:44.201Z level=INFO source=images.go:863 msg="total blobs: 6"
time=2024-02-17T22:16:44.212Z level=INFO source=images.go:870 msg="total unused blobs removed: 0"
time=2024-02-17T22:16:44.214Z level=INFO source=routes.go:999 msg="Listening on [::]:11434 (version 0.1.24)"
time=2024-02-17T22:16:44.214Z level=INFO source=payload_common.go:106 msg="Extracting dynamic libraries..."
time=2024-02-17T22:16:49.285Z level=INFO source=payload_common.go:145 msg="Dynamic LLM libraries [cpu_avx2 rocm_v6 cuda_v11 cpu_avx cpu rocm_v5]"
time=2024-02-17T22:16:49.285Z level=INFO source=gpu.go:94 msg="Detecting GPU type"
time=2024-02-17T22:16:49.285Z level=INFO source=gpu.go:242 msg="Searching for GPU management library libnvidia-ml.so"
time=2024-02-17T22:16:49.286Z level=INFO source=gpu.go:288 msg="Discovered GPU libraries: []"
time=2024-02-17T22:16:49.286Z level=INFO source=gpu.go:242 msg="Searching for GPU management library librocm_smi64.so"
time=2024-02-17T22:16:49.286Z level=INFO source=gpu.go:288 msg="Discovered GPU libraries: []"
time=2024-02-17T22:16:49.286Z level=INFO source=cpu_common.go:11 msg="CPU has AVX2"
time=2024-02-17T22:16:49.286Z level=INFO source=routes.go:1022 msg="no GPU detected"
[GIN] 2024/02/17 - 22:17:22 | 200 |     143.649µs |      10.244.0.5 | GET      "/"
[GIN] 2024/02/17 - 22:18:14 | 200 |      57.729µs |      10.244.0.5 | GET      "/"
[GIN] 2024/02/17 - 22:19:41 | 200 |      39.129µs |      10.244.0.5 | GET      "/"

but still undefined even after restarting

**Comment by 9876691** [comment]
@nsunder72 I've updated the K8's operator to use the correct port.

Your service should be port 11434 and targetPort 11434

Let me know how it goes.

**Comment by 9876691** [comment]
Closing, re-open if issue persists.

**Comment by nsunder72** [comment]
i've re apply 
kubectl apply -n bionic-gpt -f https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/crates/k8s-operator/config/bionic-operator.yaml
and
kubectl apply -n bionic-gpt -f https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/crates/k8s-operator/config/bionic.yaml
then restart the container but error undefined persist. the processing takes time though. 
i don't know how to investigate further
