### ISSUE TITLE
Empty responses

### ISSUE THREAD

**Issue by IrishAce** [bionic-gpt/bionic-gpt#383]
### Describe your issue

There is no response to messages when accessing a dataset.

At the start and before any datasets were created, everything ran fine, albeit slow. After I uploaded 3 .txt documents, it does not provide any response. It won't even respond when prompt option is set back to 'Exclude All Datasets'. 

### Describe your setup/startup scripts

There are 2 datasets:
• Default (Exclude All Datasets)
• Relevant History

There is 1 dataset, which contains 4 files (3 .txt, 1 .pdf)

In the Chat Console, the prompt option is set to 'Relevant History' and a brief question is submitted. The console shows the model: llama2 processing prompt, and then it disappears with no response.

### Steps to reproduce

1. Goto [Team Datasets]
2. "+" Add Dataset
3. Set Name: "Relevant History"
4. Set Who has visibility?: 'Just Me'
5. Goto []Advanced Configuration: no changes made to default settings
6. Click <Create Dataset>
7. On the 'Relevant History/Documents' page:
8. Set Name: "Relevant History"
9. Set Who has visibility?: 'Just Me'
10. []Advanced Configuration: no changes made to default settings
11. Click <Create Dataset>
12. Click <Add a Document>
13. Click <Browse>
14. Select files to upload, Click <Open>
15. Click <Upload Files> ...files complete processing
16. Goto [Prompts]
17. "+" New Prompt
18. Set Name: "Relevant"
19. Set Who has visibility?: 'Private'
20. Select model: 'llama2'
21. Edit Prompt: 'Analyze and process a response based on...'
22. Goto []Datasets: selected "Relevant History"
23. Goto []Advanced: no changes made to default settings
24. Click <Submit>
25. Goto [Chat Console]
26. Set Prompt: "Relevant"
27. Enter text in box & <Send Message>
28. Text pops up in console, followed by (Model:llama2) & (Stop Processing)
29. A spinning circle icon displays below with "Processing prompt"
30. After a few seconds, the "Processing prompt" disappears and (Stop Processing) changes to (View Prompt)

### Any additional information

When reviewing the (View Prompt)>Full Prompt

- Code is shown in the box
- 'Context provided to the prompt from your documents' lists a series of "A section from Page..." actions

This is a bit from the Terminal from processing this action:

patm-app-1    | 2024-02-23T22:12:37.006488Z  INFO embeddings_api: Processing 384 bytes
patm-app-1    | 2024-02-23T22:12:37.006719Z  INFO axum_server::prompt: prompt.name="Relevant History"
patm-app-1    | 2024-02-23T22:12:37.009324Z  INFO axum_server::prompt: Retrieved 72 chunks
patm-app-1    | 2024-02-23T22:12:37.010206Z  INFO axum_server::prompt: Retrieved 0 history items
patm-app-1    | 2024-02-23T22:12:37.010272Z  INFO axum_server::prompt: Using context size of 14757395478869966848
patm-oauth2-proxy-1    _[REDACTED]_

**Comment by 9876691** [comment]
Which setup are you using i.e which docker compose files or are you on enterprise?

**Comment by IrishAce** [comment]
Docker 4.24.0 installed. _(I'm limited with macOS 11 Big Sur)_

**Comment by 9876691** [comment]
No, which `docker-compose.yml` files are you using.

**Comment by IrishAce** [comment]
I'm sorry for the misunderstanding. I have not made any changes to the default files yet. This is my current `docker-compose.yml` configuration:

https://github.com/IrishAce/bionic-gpt/blob/main/.devcontainer/docker-compose.yml

**Comment by 9876691** [comment]
@IrishAce Sorry, one more question. What system are you on i.e. Windows, Linux etc and how much memory do you have?

**Comment by IrishAce** [comment]
No apologies needed - I appreciate any bit of help!

macOS v11.7 Big Sur
4 GHz Quad-Core Intel Core i7
32 GB RAM
AMD Radeon R9 M295X

**Comment by andreishiresfuse** [comment]
Hey - I just had this issue. I think there is a typo in the default docker-compose. 
The proxy is timing out waiting for the LLM to answer because OAUTH2_PROXY_UPSTREAMS_TIMEOUT should actually be OAUTH2_PROXY_UPSTREAM_TIMEOUT (note the S has been removed there).
Your mileage may vary but it works for me.

**Comment by 9876691** [comment]
@andreishiresfuse Thanks, for this, good spot. I've updated the `docker compose` files.

**Comment by 9876691** [comment]
If this issue persists, please re-open.
