### ISSUE TITLE
ollama and llm-api (litellm) would conflict on port 11434

### ISSUE THREAD

**Issue by jtara1** [bionic-gpt/bionic-gpt#385]
### Describe your issue

The docs for bionic-gpt might just be out of date.  

Running ollama LLM backend https://bionic-gpt.com/docs/running-locally/gpu-setup-ollama/

but it's confusing bc it instructs us to run ollama ourselves which binds to and publishes port 11434 by default, but the docker-compose-ollama.yml pulls llm-api which binds to the same port.

At a glance, it looks like litellm and ollama are 2 different things, which would suggest a breaking code change and not just old docs?

This is the commit that made the change b3000c2bc15fde7206040a06bc8ee158ee1a045a 

Not sure why this issue, asking about ollama, was closed https://github.com/bionic-gpt/bionic-gpt/issues/298

### Describe your setup/startup scripts

from https://bionic-gpt.com/docs/running-locally/gpu-setup-ollama/
```
curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose/docker-compose.yml
curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/main/docker-compose/docker-compose-ollama.yml
docker-compose -f docker-compose.yml -f docker-compose-ollama.yml up
```

^ would result in broken app bc no LLM backend I believe

### Steps to reproduce

1. go to http://localhost:7800/app/team/1/console
2. enter some message like `hello`
3. processing takes inf time, check logs

**Comment by 9876691** [comment]
@jtara1 I've updated the docs and changed the `docker-compose.yml`.

Re-open if you still have issues.
