### ISSUE TITLE
 [main.go:60] ERROR: Failed to initialise OAuth2 Proxy

### ISSUE THREAD

**Issue by duhaly** [bionic-gpt/bionic-gpt#389]
when use docker compose up 
oauth2-proxy-1    | [2024/03/04 06:37:58] [provider.go:55] Performing OIDC Discovery...
oauth2-proxy-1    | [2024/03/04 06:37:58] [main.go:60] ERROR: Failed to initialise OAuth2 Proxy: error initialising provider: could not create provider data: error building OIDC ProviderVerifier: could not get verifier builder: error while discovery OIDC configuration: failed to discover OIDC configuration: unexpected status "502":
why?how to ?

**Comment by 9876691** [comment]
@duhaly Normally happens while keycloak is starting, has the issue resolved itself already?

**Comment by 9876691** [comment]
Closing, let me know if this is still an issue.

**Comment by duhaly** [comment]
@9876691 dc4a9c20b1ee   ghcr.io/bionic-gpt/bionicgpt-keycloak:1.6.10     "/opt/keycloak/bin/k…"   2 days ago   Up 3 hours (healthy)            8080/tcp, 0.0.0.0:7810->7810/tcp, :::7810->7810/tcp, 8443/tcp   bionic-keycloak-1
the issue is still
