### ISSUE TITLE
Cannot install BionicGPT enterprise -  k3s.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by felixnguyen258** [bionic-gpt/bionic-gpt#418]
### Describe your issue

 k3s.service: Failed with result 'exit-code' after follow the installation step for BionicGPT enterprise.

Link: https://bionic-gpt.com/docs/enterprise-edition/preparation/

### Describe your setup/startup scripts

Following installation step at
https://bionic-gpt.com/docs/enterprise-edition/preparation/

### Steps to reproduce

Go to terminal and execute command line which is mentioned from the url:
https://bionic-gpt.com/docs/enterprise-edition/preparation/

It failed to start the Kubernetes and return "Failed with result 'exit-code'"
[failed_log.txt](https://github.com/bionic-gpt/bionic-gpt/files/14770371/failed_log.txt)

**Comment by 9876691** [comment]
Hi Felix,

The enterprise docs are not really ready yet. You can continue to sue the community version
