### ISSUE TITLE
When commiting website only changes can we not run full build script

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#42]

**Comment by kulbinderdio** [comment]
Still an issue. Not able to commit changes to web site, due to 

   Compiling db v0.1.0 (/workspace/crates/db)
    Checking cornucopia_async v0.4.0
   Compiling dioxus-core-macro v0.4.1 (https://github.com/DioxusLabs/dioxus.git?rev=d8704a0#d8704a04)
   Compiling assets v0.1.0 (/workspace/crates/asset-pipeline)
    Checking dioxus-ssr v0.4.1 (https://github.com/DioxusLabs/dioxus.git?rev=d8704a0#d8704a04)
    Checking reqwest v0.11.20
   Compiling regex-automata v0.3.4
    Checking multer v2.1.0
    Checking bit-set v0.5.3
    Checking rustls-native-certs v0.6.3
    Checking tracing-subscriber v0.3.17
    Checking axum-core v0.3.4
error: failed to run custom build command for `db v0.1.0 (/workspace/crates/db)`

Caused by:
  process didn't exit successfully: `/workspace/target/debug/build/db-2aa66545dd36e1c5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=queries

  --- stderr
  thread 'main' panicked at 'Error:   × Couldn't prepare query: column a.user_id does not exist
     ╭─[queries/api_keys.sql:7:1]
   7 │     a.prompt_id,
   8 │     a.user_id,
     ·     ▲
     ·     ╰── error occurs near this location
   9 │     (SELECT name FROM prompts p WHERE p.id = a.prompt_id) as prompt_name,
     ╰────

  ', crates/db/build.rs:39:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
There are some clippy issues, run 'cargo clippy' first.
/workspace (website)

**Comment by ianpurton** [comment]
Workaround is to run `dbmate up` first.

**Comment by ianpurton** [comment]
Use `--no-verify` to skip the githooks.
