### ISSUE TITLE
The cluster is not correctly addressable when accessed via an SSH tunnel

### ISSUE THREAD

**Issue by vkomenda** [bionic-gpt/bionic-gpt#428]
### Describe your issue

My GPU server only opens the SSH port to the internet. External accesses are done using SSH tunnels. Opening the landing page redirects to the auth pod at address which is only valid on the server. It's unreachable from the other end of the SSH tunnel. Here are the running pods with their IP addresses:

![image](https://github.com/bionic-gpt/bionic-gpt/assets/5529505/336ee6fd-8e43-404d-b5e7-eb704cb2029f)

How to manage IP redirects in this setup?

### Describe your setup/startup scripts

1. Bionic GPT enterprise setup [instructions] (https://bionic-gpt.com/docs/enterprise-edition/bare-metal/) on the server.
2. SSH tunnel from the laptop to the Bionic GPT server:
`ssh -fNT -p<SERVER_SSH_PORT> -L 3333:localhost:80 USER@SERVER`

### Steps to reproduce

1. open http://localhost:3333

This redirects to an intranet IP unreachable from the laptop. 

### What was the expected result?

The auth page.

**Comment by 9876691** [comment]
Keycloak needs to know how to do the redirect.

If you install again you can pass this into the cli.

```sh
bionic install --hostname-url http://localhost:3333
```

**Comment by vkomenda** [comment]
Thanks! To reinstall, s correctlyhould I delete the bionic-gpt namespace and restart k3s?

**Comment by vkomenda** [comment]
After reinstalling k3s, I get this on the server
```
$ bionic install --hostname-url http://localhost:3333
Waiting for Cloud Native Postgres Controller Manager
Waiting for Bionic CRD
When ready you can access bionic on http://10.17.7.50
```

and "404 page not found" in the browser.

**Comment by 9876691** [comment]
There's a new version of the CLI that has a fix for this. Let me know how it goes.

**Comment by vkomenda** [comment]
I get a 404 error at `https://github.com/bionic-gpt/bionic-gpt/releases/latest/download/bionic-cli-linux`

**Comment by vkomenda** [comment]
I've downloaded the Linux release. It's working now. Thanks for the fix!
