### ISSUE TITLE
"try it out" running locally link down

### ISSUE THREAD

**Issue by pierro42** [bionic-gpt/bionic-gpt#431]
### Describe your issue

"try it out" link is down

https://github.com/bionic-gpt/bionic-gpt?tab=readme-ov-file#try-it-out

https://bionic-gpt.com/docs/running-locally/introduction/

### Describe your setup/startup scripts

Just click on the link

### Steps to reproduce

Just click on the link

**Comment by 9876691** [comment]
It's back now. Thanks for that.
