### ISSUE TITLE
docker compose file has been removed

### ISSUE THREAD

**Issue by dav-ko** [bionic-gpt/bionic-gpt#444]
### Describe your issue

The docker-compose file has been removed.

### Describe your setup/startup scripts

Up until recently, a docker-compose.yml was available for easy non-production setup.
Since this does not seem to be available anymore, I wanted to enquire if there are plans for a new (non-)production version of the file. 

### Steps to reproduce

1. Go to Github repo

**Comment by 9876691** [comment]
@dav-ko No we won't be introducing it. People were using it to deploy the app in a non secure way.

The k3s way is easy to do and way more secure.
