### ISSUE TITLE
No response being geenrated

### ISSUE THREAD

**Issue by rpaGuyai** [bionic-gpt/bionic-gpt#450]
I have installed Bionic GPT on Windows and launched the terminal interface but unfortunately I do not get any response to the query.
I have even added my own data set, tried custom prompt still same.
![image](https://github.com/bionic-gpt/bionic-gpt/assets/154881376/e67083ad-6300-460f-8224-2dbcc4594178)

**Comment by 9876691** [comment]
Can you show a screenshot of your model setting screen?
