### ISSUE TITLE
Long response gets cut  off with error message

### ISSUE THREAD

**Issue by rpaGuyai** [bionic-gpt/bionic-gpt#464]
### Describe your issue

When I ask some question which will have longer response, the response seems to be cut off after certain tokens.
Screenshot -1 - it starts to generate reposing
Screenshot -2 - It cuts off the response with error message.

Smaller response still works.

### Describe your setup/startup scripts

I am using Default Prompt.
OS - Windows 11 Pro

### Steps to reproduce

Go to all chats and type
![image](https://github.com/bionic-gpt/bionic-gpt/assets/154881376/fc34b52b-8bf8-4807-bc8d-fde2c83585c4)
 ' Write a story for a bout 500 words'

![image](https://github.com/bionic-gpt/bionic-gpt/assets/154881376/d7f67f35-ca77-4a28-90e7-b84bae1da412)

**Comment by 9876691** [comment]
How much memory do you have?

**Comment by rpaGuyai** [comment]
![image](https://github.com/bionic-gpt/bionic-gpt/assets/154881376/e01b33eb-0bed-43cf-a87e-8dade8c55c65)

We especially purchased this machine with GPU to run private models

**Comment by rpaGuyai** [comment]
Ohh...so you were able to replicate the error on your side as well? what do you think could be the cause, strangely when I run on another laptop on Windows 10, it works perfectly, so couldn't get the exact error cause.

**Comment by 9876691** [comment]
It may be something to do with the traefik ingress timing out if it thinks the request is over.

That's where I will start to look.

**Comment by rpaGuyai** [comment]
Thanks, strangely it works perfectly  on Windows 11 Home but doesn't work on Windows 11 Pro, not sure if it's OS related issue.

**Comment by 9876691** [comment]
I don't think it's OS related as I'm running on Linux :)

I will upgrade the LLama model and inference engine and see what we get.

**Comment by rpaGuyai** [comment]
I see, so you are facing the same issue on Linux as well, okay will wait for your solution, meanwhile I am also trying to find a fix but we did try upgrading/degrading LLama model.

**Comment by 9876691** [comment]
Can you tell me what version you are using?

**Comment by rpaGuyai** [comment]
Appreciate your prompt response and fix, the new .exe works.
