### ISSUE TITLE
Unable to install bionic-gpt community edition

### ISSUE THREAD

**Issue by jawmodou** [bionic-gpt/bionic-gpt#476]
### Describe your issue

We are trying to build and AI chatbot internally and we are impressed by bionic application. However, we are unable to install the community edition https://bionic-gpt.com/docs/community-edition/installation/ after following the instructions.

```shell
Error: ApiError: "service unavailable\n": Failed to parse error data (ErrorResponse { status: "503 Service Unavailable", message: "\"service unavailable\\n\"", reason: "Failed to parse error data", code: 503 })

Caused by:
    "service unavailable\n": Failed to parse error data
```

### Describe your setup/startup scripts

OS : Ubuntu:  5.15.0-105-generic
GPU: 4090 NVIDIA 
https://bionic-gpt.com/docs/community-edition/installation/

### Steps to reproduce

Followed the instruction in this link:
https://bionic-gpt.com/docs/community-edition/installation/
It failed during ```bionic install```

### What was the expected result?

Successfully run the bionic install

**Comment by Archjuna** [comment]
Hello,

Have you any error in your journal : `systemctl status k3s`  ?

If you have : 
```
…
failed to pull image \\\"rancher/mirrored-pause:3.6\\\"
…
```
Maybe it's your `/etc/resolve.conf`.  Try : 
```bash
sudo k3s ctr image pull docker.io/rancher/mirrored-pause:3.6
```
If you can't pull the image, it's maybe your `/etc/resolve.conf`.
You can : 
```bash
sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
```
