### ISSUE TITLE
Failed to add document to dataset 

### ISSUE THREAD

**Issue by seliuchenko** [bionic-gpt/bionic-gpt#496]
### Describe your issue

When i add document to dataset from web interface, i get error message in logs and status of the document is forever Processing. 
![image](https://github.com/bionic-gpt/bionic-gpt/assets/10779090/da0bf31d-66df-437d-85c8-c0d85ce5a846)

### Describe your setup/startup scripts

I set up bionic with this guide, https://bionic-gpt.com/docs/community-edition/docker-compose/
All launches successfully.

### Steps to reproduce

Open localhost:3000
Create new dataset
Add document
Attach file (txt 19 bytes, tried also pdf, doc)
Document is shown in UI with status Processing (and stays forever)
In console logs error: pipeline-job-1     | 2024-05-25T06:57:40.039603Z ERROR pipeline_job: error="Not able to parse document error sending request for url (http://unstructured:8000/general/v0/general)"
Same result for v1.7.15/12/12.
OS win 11, Docker  4.29.0

**Comment by 9876691** [comment]
Hi this was fixed in 1.7.16 see https://github.com/bionic-gpt/bionic-gpt/issues/491

Could you try again.

```sh
curl -O https://raw.githubusercontent.com/bionic-gpt/bionic-gpt/v1.7.16/infra-as-code/docker-compose.yml
```

**Comment by seliuchenko** [comment]
thanks, I ll try, fyi, your yml file for 1.7.16 still has 1.7.15 inside, i replaced it manually, will check and reply back after testing
![image](https://github.com/bionic-gpt/bionic-gpt/assets/10779090/713cc5a7-39cb-4f73-b8b9-cd3a13f463d5)

**Comment by 9876691** [comment]
@seliuchenko Thanks, re-opening this.

CI/CD pipeline not updating versions in docker-compose.yml

**Comment by seliuchenko** [comment]
I confirm in 1.7.16 the issue is resolved. The parsing of documents goes through successfully.

**Comment by 9876691** [comment]
@seliuchenko Thnaks.
