### ISSUE TITLE
Implement Testing UI

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#54]
Allow people to enter a series of prompts and run them.

Allow people to evaluate and score the results.

Keep track of model, prompt, chunking strategy etc.

- [ ] Use Cases
- [ ] Test Runs
- [ ] Run unstructured process in the background
- [ ] Detach prompt and dataset. 
- [ ] User can select dataset at the console.
- [ ] Use case has 1 or more questions - Attach to a prompt and a dataset.
- [ ] Test Runs capture all variables.
- [ ] Run in background
- [ ] After the run user can evaluate the results.

**Comment by kulbinderdio** [comment]
can we get timings for different parts of the pipeline?
Also allow selection for different RAG techniques such as double hit on LLM by first asking it to rewrite prompt in a better way to answer the specific question. Will update with other techniques later

**Comment by ianpurton** [comment]
Out of scope at the moment.
