### ISSUE TITLE
Enhance AI Assistants

### ISSUE THREAD

**Issue by tiswas247** [bionic-gpt/bionic-gpt#554]
- [x] Change view to cards
- [x] New tab with example prompts. (4 boxes?) What does chat gpt do.
- [x] Allow user to set example prompts.
- [x] Empty chat screen should show AI assitant details and prompt examples (see screenshot)
- [x] Disclaimer message i.e. LLMs can make mistakes. Check important info.
- [ ] Only person who created prompt can see details?
- [ ] Ability to clone an assistant.
- [ ] Choose an icon or upload an image
- [x] Delete chat (Make it work)
- [x] New chat (Make it work)

## DB

```sql
ALTER TABLE prompts ADD COLUMN description VARCHAR NOT NULL DEFAULT 'Please add a description';
ALTER TABLE prompts ADD COLUMN disclaimer VARCHAR NOT NULL DEFAULT 'LLMs can make mistakes. Check important info.';
ALTER TABLE prompts ADD COLUMN example1 VARCHAR;
ALTER TABLE prompts ADD COLUMN example2 VARCHAR;
ALTER TABLE prompts ADD COLUMN example3 VARCHAR;
ALTER TABLE prompts ADD COLUMN example4 VARCHAR;

```

## How Chat GPT does it

![image](https://github.com/user-attachments/assets/3c3924af-0370-44da-9a09-2efd9f8893c0)

## Card presentation

![image](https://github.com/user-attachments/assets/59c506df-86c6-4759-9fb7-2e45f3b63f70)

**Comment by tbendien** [comment]
These updates look awesome!!! Pls post screenshots for a looksee if you can?

**Comment by tbendien** [comment]
need to be able to sort assistants alphabetically and search on keywords in the assistant catalog to find a specific assistant or a set of assistants e.g. all the assistants for a certain teacher or course.
