### ISSUE TITLE
Embeddings do not appear to be working in v.1.7.47

### ISSUE THREAD

**Issue by HackWeasel** [bionic-gpt/bionic-gpt#574]
### Describe your issue

When uploading a file to a dataset, the embedding process seems to fail, making no progress.

### Describe your setup/startup scripts

We did a Linux install with k3s.

### Steps to reproduce

1. Create new dataset.
2. Upload file to dataset.
3. Embedding does not progress, and just hangs.
![47 embedding bug](https://github.com/user-attachments/assets/2820f771-a815-435e-972a-eff58a2ba6f6)

### What was the expected result?

I expected to be able to embed the uploaded file in the dataset.

**Comment by kulbinderdio** [comment]
Are you able to upload the file to this issue?

**Comment by HackWeasel** [comment]
[crime and punishment test.txt](https://github.com/user-attachments/files/16718967/crime.and.punishment.test.txt)


> Are you able to upload the file to this issue?

**Comment by tbendien** [comment]
this was for version 1.7.47.

It's possible that there was a browser related caching issue. Sometimes logging out and logging back in again helps with things like this.

We will try the new version 1.7.48 and make sure that its ok.

**Comment by HackWeasel** [comment]
After some troubleshooting, we discovered that the issue was an improperly formatted file name uploaded from a linux host.
