### ISSUE TITLE
embedding Model drop down empty

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#75]
With existing yml file I ran - docker compose down -v
Downloaded latest yml file using new curl command 
brought up containers (required download of new containers)
Created new user and tried to add new dataset

Embedding Model dropdown empty

**Comment by ianpurton** [comment]
This is part of a wider issue see https://github.com/pgvector/pgvector/issues/324

We want to allow users to be able to use different embeddings models, but pgVector fixes the dimensions.

So either users have to change the dimension in the DB.

We also moved over to https://github.com/huggingface/text-embeddings-inference which is a more production ready method of embeddings inference and supports GPU.

**Comment by kulbinderdio** [comment]
There is an update on 324, if that doesn't work could we do something, that I believe is used for training LLMs, the idea of padding. So we define a much larger vector size and depending on our embedding model we pad out where required. What the impact on data usage etc would be I don't know.
