### ISSUE TITLE
Document uploading not working

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#79]
Downloaded latest config file
Created a new embedding  https://api.openai.com/v1/embeddings

tried to upload pdf document, getting the following errors showing in log (nothing on front end)

fine-tuna-barricade-1       | [2023-11-01T11:38:55Z INFO  actix_web::middleware::logger] 172.23.0.4 "POST /app/team/2/dataset/1/doc_upload HTTP/1.1" 200 0 "-" "-" 0.000627
fine-tuna-barricade-1       | [2023-11-01T11:38:55Z INFO  sqlx::query] /* SQLx ping */; rows affected: 0, rows returned: 0, elapsed: 94.555µs
fine-tuna-app-1             | 2023-11-01T11:38:55.147453Z  INFO axum_server::documents::upload_doc: Sending document to unstructured
fine-tuna-unstructured-1    | 2023-11-01 11:38:56,767 unstructured_api DEBUG pipeline_api input params: {"filename": "MSFT_FY23Q4_10K.pdf", "response_type": "application/json", "m_coordinates": [], "m_encoding": [], "m_hi_res_model_name": [], "m_include_page_breaks": [], "m_ocr_languages": [], "m_pdf_infer_table_structure": [], "m_skip_infer_table_types": [], "m_strategy": [], "m_xml_keep_tags": [], "languages": ["eng"], "m_chunking_strategy": ["by_title"], "m_multipage_sections": ["true"], "m_combine_under_n_chars": ["500"], "new_after_n_chars": ["1000"]}
fine-tuna-unstructured-1    | 2023-11-01 11:38:56,768 unstructured_api DEBUG filetype: application/pdf
fine-tuna-unstructured-1    | 2023-11-01 11:38:56,835 unstructured_api DEBUG partition input data: {"content_type": "application/pdf", "strategy": "auto", "ocr_languages": null, "coordinates": false, "pdf_infer_table_structure": false, "include_page_breaks": false, "encoding": null, "model_name": null, "xml_keep_tags": false, "skip_infer_table_types": ["pdf", "jpg", "png"], "languages": ["eng"], "chunking_strategy": "by_title", "multipage_sections": true, "combine_under_n_chars": 500, "new_after_n_chars": 1000}
fine-tuna-unstructured-1    | 2023-11-01 11:38:57,253 172.23.0.8:58440 POST /general/v0/general HTTP/1.1 - 500 Internal Server Error
fine-tuna-app-1             | 2023-11-01T11:38:57.254773Z ERROR axum_server::errors: response="status = 422 Unprocessable Entity, message = error decoding response body: invalid type: map, expected a sequence at line 1 column 0"
[MSFT_FY23Q4_10K.pdf](https://github.com/bionic-gpt/bionic-gpt/files/13226535/MSFT_FY23Q4_10K.pdf)

**Comment by ianpurton** [comment]
Looks like an issue with unstructured

```sh
curl -X 'POST' 'http://unstructured:8000/general/v0/general'
 -H 'accept: application/json' -H 'Content-Type: multipart/for
m-data' -F 'files=@MSFT_FY23Q4_10K.pdf'
```

gives the result

```sh
{"detail":"local variable 'isalnum' referenced before assignment"}
```

**Comment by ianpurton** [comment]
Latest version of unstructured fixes this. I've updated the `docker-compose.yml`
