### ISSUE TITLE
Add Oobabooga API to Models

### ISSUE THREAD

**Issue by gregrobison** [bionic-gpt/bionic-gpt#80]
How do I add my locally running Oobabooga textgen installation with api and openapi extensions to the Model Setup tab? Thanks.

**Comment by ianpurton** [comment]
@gregrobison Hi, did you try this https://bionic-gpt.com/docs/administration/external-api/

**Comment by gregrobison** [comment]
I tried a few different API settings trying to get it to connect, but it always resulted in an error. Do I need to open any ports in Docker?

**Comment by ianpurton** [comment]
You don't need to open any ports.

One thing to try is from the command line is to run something like

```sh
curl -N http://localhost:5000/v1/chat/completions -H "Content-Type: application/json" -d '{
     "stream" : true,
     "model": "llama2-chat", 
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.1 
   }'
```

You'll need to change the port (5000) to the port you are running on. You might also need to change the model parameter.

If this works then take convert the `localhost` to `host.docker.internal` and the URL for entry in the GUI should be something like

`http://host.docker.internal:PORT/v1`

Note the v1 at the end.

**Comment by gregrobison** [comment]
I get "The underlying connection was closed: An unexpected error occurred on a receive." on port 5000 (which the api says it is running on) or "The underlying connection was closed: The connection was closed unexpectedly." using http://localhost:5005/api/v1/stream.

**Comment by ianpurton** [comment]
I'm a bit confused you said the API is running on 5000, I'm assuming you mean the oobabooga open AI API?

Then you try to connect on 5005?

Thanks

**Comment by gregrobison** [comment]
I'm confused too (I am a novice)! Oobabooga says "INFO:Streaming API URL:
wss://0.0.0.0:5005/api/v1/stream
INFO:Blocking API URL:
https://0.0.0.0:5000/api"
So I've tried various settings combinations to try to get it connect.

**Comment by gregrobison** [comment]
I've enabled the new --openai extension instead of --api and see INFO:OpenAI compatible API URL:
https://0.0.0.0:5000/v1, but when entering that info for the model, I still get an error.

**Comment by ianpurton** [comment]
@gregrobison Glad you got it working. I'll close this out.
