### ISSUE TITLE
Model for Default prompt is bge-small-en-v1.5

### ISSUE THREAD

**Issue by kulbinderdio** [bionic-gpt/bionic-gpt#83]
By having this as the default model chat doesn't return anything.
SHould default to llama  model

**Comment by ianpurton** [comment]
That's fixed.

The wider issue is that bugs like this get through while I'm not running the integration tests as part of CI/CD.

I have a strategy for that so will make this a priority https://github.com/bionic-gpt/bionic-gpt/issues/7
