### ISSUE TITLE
How to clear console records

### ISSUE THREAD

**Issue by JohnKeng** [bionic-gpt/bionic-gpt#84]
![image](https://github.com/bionic-gpt/bionic-gpt/assets/1924712/906e3040-c081-468b-bf85-9ba7d7d8f39f)

**Comment by JohnKeng** [comment]
Can't clear the chat console

**Comment by ianpurton** [comment]
@JohnKeng Thanks for raising this.

I want to add a chat history to track new conversations etc so that would include this.

I'll prioritise it.
